(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const client=()=>window.LangarAdminCloud?.client||null;
let known=new Set(),primed=false,audio=null,lastAlert='';
function unlockAudio(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch{}}
document.addEventListener('pointerdown',unlockAudio,{once:false,capture:true});
function tone(freq,when,dur=.16,g=.12){try{unlockAudio();if(!audio||audio.state!=='running')return;const o=audio.createOscillator(),v=audio.createGain();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(.001,when);v.gain.exponentialRampToValueAtTime(g,when+.02);v.gain.exponentialRampToValueAtTime(.001,when+dur);o.connect(v);v.connect(audio.destination);o.start(when);o.stop(when+dur+.03)}catch{}}
function escalating(){try{unlockAudio();if(!audio||audio.state!=='running')return;const t=audio.currentTime+.03;[520,660,820,1040].forEach((f,i)=>tone(f,t+i*.18,.14,.14+i*.025));setTimeout(()=>{if(audio?.state==='running'){const q=audio.currentTime+.03;[660,820,1040,1320].forEach((f,i)=>tone(f,q+i*.16,.13,.16+i*.02))}},900)}catch{}}
function toast(text){let x=$('#v610OrderToast');if(!x){x=document.createElement('div');x.id='v610OrderToast';document.body.appendChild(x)}x.textContent='🔔 '+text;clearTimeout(x._t);x._t=setTimeout(()=>x.remove(),9000)}
function openOrders(id){try{if(typeof window.showPanel==='function')window.showPanel('ordersPanel');else $$('.panel').forEach(p=>p.classList.toggle('hidden',p.id!=='ordersPanel'));localStorage.langar_admin_order_filter='live';setTimeout(()=>$('#refreshCloudOrders')?.click(),120);setTimeout(()=>{const cards=$$('.cloud-order-card');const card=cards.find(c=>c.textContent.includes(id))||cards[0];if(card){card.classList.add('v610-new-order-focus');card.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>card.classList.remove('v610-new-order-focus'),7000)}},700)}catch(e){console.warn('[V610] focus order',e)}}
async function poll(){const c=client();if(!c||document.body.classList.contains('admin-locked'))return;try{const {data,error}=await c.from('customer_orders').select('id,order_number,status,is_test,created_at').eq('is_test',false).in('status',['new','accepted','preparing','ready']).order('created_at',{ascending:false}).limit(60);if(error)throw error;const ids=new Set((data||[]).map(x=>String(x.id)));if(!primed){known=ids;primed=true;return}const fresh=(data||[]).filter(x=>!known.has(String(x.id)));known=ids;if(!fresh.length)return;const first=fresh[0],sig=String(first.id);if(sig===lastAlert)return;lastAlert=sig;escalating();toast(`NEW ORDER ${first.order_number||sig.slice(0,8)} — opening Orders now`);openOrders(first.order_number||sig);try{if('Notification'in window&&Notification.permission==='granted')new Notification('Langar Bar — NEW ORDER',{body:`${first.order_number||sig.slice(0,8)} received. Orders panel opened automatically.`,icon:'assets/admin-icon-192.png'})}catch{}}catch(e){console.warn('[V610] order watch',e?.message||e)}}
function fixButtonText(){$$('button:not(.danger),a.secondary,a.primary').forEach(b=>{b.style.setProperty('color','#080808','important');b.querySelectorAll('*').forEach(x=>x.style.setProperty('color','#080808','important'))})}
new MutationObserver(fixButtonText).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
setInterval(fixButtonText,1800);setInterval(poll,2500);setTimeout(poll,1000);
window.LangarAdminV610={poll,unlockAudio,version:'6.1.0'};
})();
