const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const ICONS={'cat-coffee':'☕','cat-tea':'🍵','cat-matcha-smoothies':'🥤','cat-protein':'💪','cat-soft':'🧃','cat-beer-wine':'🍷','cat-combo':'✨','cat-dessert':'🍦','cat-toast':'🥪','cat-tacos':'🌮','cat-focaccia-pizza':'▰','cat-tapas':'<img src="assets/tapas_icon.jpg" alt="Tapas">'};
function getMenu(){let m=LS.get('langar_menu_v3',null); if(m){m=m.map(c=>({...c,icon:ICONS[c.id]||c.icon||'✦'})); LS.set('langar_menu_v3',m); return m;} m=LANGAR_DEFAULT_MENU.map(c=>({...c,icon:ICONS[c.id]||'✦',items:c.items.map(i=>({...i,allergens:i.isAlcoholic?'18+':'ask staff'}))})); LS.set('langar_menu_v3',m); return m;}
function saveMenu(m){LS.set('langar_menu_v3',m)}
function uid(p){return p+'-'+Math.random().toString(36).slice(2,8)+'-'+Date.now().toString(36).slice(-4)}
function priceNum(p){const m=String(p).replace(',','.').match(/[0-9]+(\.[0-9]+)?/);return m?parseFloat(m[0]):0}
function showPanel(id){$$('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==id)); renderAll();}
window.showPanel=showPanel;
function statusSelect(current){return `<select class="statusSelect"><option ${current==='new'?'selected':''}>new</option><option ${current==='accepted'?'selected':''}>accepted</option><option ${current==='preparing'?'selected':''}>preparing</option><option ${current==='ready'?'selected':''}>ready</option><option ${current==='out_for_delivery'?'selected':''}>out_for_delivery</option><option ${current==='delivered'?'selected':''}>delivered</option><option ${current==='cancelled'?'selected':''}>cancelled</option><option ${current==='rejected'?'selected':''}>rejected</option></select>`}
function renderDashboard(){const d=$('#adminDashboard'); if(!d)return; const orders=LS.get('langar_orders_v3',[]), res=LS.get('langar_reservations',[]), inbox=LS.get('langar_inbox',[]), cards=LS.get('langar_cards',[]), p=LS.get('langar_profile',null); d.innerHTML=`<button><span>🧾</span><b>${orders.length}</b><small>Orders</small></button><button><span>📅</span><b>${res.length}</b><small>Reservations</small></button><button><span>👤</span><b>${p?1:0}</b><small>Customers</small></button><button><span>🎁</span><b>${cards.filter(c=>c.status==='active').length}</b><small>Active Cards</small></button><button><span>✉</span><b>${inbox.length}</b><small>Inbox messages</small></button><button><span>🚚</span><b>${orders.filter(o=>o.status==='new').length}</b><small>New Orders</small></button>`;}
function renderQuickPrices(){const box=$('#quickPrices'); if(!box)return; const m=getMenu(); box.innerHTML=''; m.forEach(cat=>{const h=document.createElement('h3'); h.textContent=cat.title.en; box.appendChild(h); cat.items.forEach(item=>{const row=document.createElement('div'); row.className='quick-price'; row.innerHTML=`<b>${item.name}</b><input data-id="${item.id}" value="${item.price}"><small>${cat.title.hr}</small>`; box.appendChild(row);});});}
function saveQuickPrices(){const m=getMenu(); $$('#quickPrices input').forEach(inp=>{m.forEach(c=>c.items.forEach(i=>{if(i.id===inp.dataset.id)i.price=inp.value;}));}); saveMenu(m); alert('Prices saved and published.'); renderAll();}
function renderMenuAdmin(){const box=$('#menuAdmin'); if(!box)return; const m=getMenu(); box.innerHTML=''; m.forEach((cat,ci)=>{const sec=document.createElement('section'); sec.className='legal-block'; sec.innerHTML=`<h3>${cat.icon||''} ${cat.title.en} / ${cat.title.hr}</h3><label>Icon<input data-cat-icon="${cat.id}" value="${cat.icon||''}"></label><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Price</th><th>Ingredients EN</th><th>Active</th><th>Online</th><th>Save</th></tr></thead><tbody></tbody></table></div>`; const tbody=sec.querySelector('tbody'); cat.items.forEach((item,ii)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td><input data-f="name" value="${item.name.replaceAll('"','&quot;')}"></td><td><input data-f="price" value="${item.price}"></td><td><textarea data-f="descEn">${item.desc.en}</textarea><textarea data-f="descHr">${item.desc.hr}</textarea></td><td><input type="checkbox" data-f="available" ${item.available!==false?'checked':''}></td><td><input type="checkbox" data-f="orderable" ${item.orderable!==false?'checked':''}></td><td><button class="secondary saveItem">Save</button><button class="danger delItem">Del</button></td>`; tr.querySelector('.saveItem').onclick=()=>{item.name=tr.querySelector('[data-f=name]').value; item.price=tr.querySelector('[data-f=price]').value; item.desc.en=tr.querySelector('[data-f=descEn]').value; item.desc.hr=tr.querySelector('[data-f=descHr]').value; item.available=tr.querySelector('[data-f=available]').checked; item.orderable=tr.querySelector('[data-f=orderable]').checked; saveMenu(m); alert('Item saved/published.'); renderAll();}; tr.querySelector('.delItem').onclick=()=>{if(confirm('Delete item?')){cat.items.splice(ii,1); saveMenu(m); renderAll();}}; tbody.appendChild(tr);}); box.appendChild(sec);}); $$('[data-cat-icon]').forEach(inp=>inp.onchange=()=>{const menu=getMenu(); const c=menu.find(x=>x.id===inp.dataset.catIcon); if(c)c.icon=inp.value; saveMenu(menu); renderAll();});}
function addItem(){const m=getMenu(); const catId=prompt('Category ID (example: cat-coffee, cat-tacos, cat-focaccia-pizza)'); const cat=m.find(c=>c.id===catId); if(!cat)return alert('Category not found.'); const name=prompt('Item name'); if(!name)return; cat.items.push({id:cat.id+'-'+(cat.items.length+1)+'-'+Date.now(),name,desc:{hr:'Opis / sastojci',en:'Description / ingredients'},price:'€0.00',available:true,orderable:true,rewardEligible:true,allergens:'ask staff'}); saveMenu(m); renderAll();}
function renderOrders(){const box=$('#ordersAdmin'); if(!box)return; const orders=LS.get('langar_orders_v3',[]); if(!orders.length){box.innerHTML='<p class="muted">No orders yet.</p>';return} box.innerHTML=`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Paid / Complete</th></tr></thead><tbody></tbody></table>`; const tb=box.querySelector('tbody'); orders.forEach((o,idx)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td><b>${o.id}</b><br><small>${new Date(o.createdAt).toLocaleString()}</small><br>${o.type}</td><td>${o.name||'-'}<br>${o.phone||''}<br>${o.address||''}</td><td>${o.items.map(i=>`${i.qty}× ${i.name}`).join('<br>')}<br><small>${o.note||''}</small></td><td>€${(+o.total).toFixed(2)}</td><td>${statusSelect(o.status)}</td><td><label><input type="checkbox" class="paid" ${o.paid?'checked':''}> Paid</label><button class="secondary complete">Save Status</button></td>`; tr.querySelector('.complete').onclick=()=>{o.status=tr.querySelector('.statusSelect').value; o.paid=tr.querySelector('.paid').checked; if(o.status==='delivered'&&o.paid&&!o.rewardPosted){postOrderReward(o); o.rewardPosted=true;} orders[idx]=o; LS.set('langar_orders_v3',orders); alert('Order updated. Rewards posted if applicable.'); renderAll();}; tb.appendChild(tr);});}
function postOrderReward(order){let p=LS.get('langar_profile',null); if(!p)return; p.orders=(p.orders||0)+1; p.visits=(p.visits||0)+1; const credit=+(order.total*0.10).toFixed(2); p.credit=+(p.credit||0)+credit; LS.set('langar_profile',p); const hist=LS.get('langar_history',[]); hist.unshift({type:'earn',text:`Order ${order.id}: €${credit.toFixed(2)} Langar Credit`,createdAt:new Date().toISOString()}); LS.set('langar_history',hist);}
function renderReservations(){const box=$('#reservationsAdmin'); if(!box)return; const arr=LS.get('langar_reservations',[]); if(!arr.length){box.innerHTML='<p class="muted">No reservations yet.</p>';return} box.innerHTML=`<table class="table"><thead><tr><th>Date/Time</th><th>Customer</th><th>Guests</th><th>Note</th><th>Status</th></tr></thead><tbody></tbody></table>`; const tb=box.querySelector('tbody'); arr.forEach((r,idx)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.date}<br>${r.time}</td><td>${r.name}<br>${r.phone}</td><td>${r.guests}</td><td>${r.note||''}</td><td><select><option ${r.status==='pending'?'selected':''}>pending</option><option ${r.status==='confirmed'?'selected':''}>confirmed</option><option ${r.status==='cancelled'?'selected':''}>cancelled</option><option ${r.status==='completed'?'selected':''}>completed</option></select><button class="secondary">Save</button></td>`; tr.querySelector('button').onclick=()=>{r.status=tr.querySelector('select').value; arr[idx]=r; LS.set('langar_reservations',arr); renderReservations();}; tb.appendChild(tr);});}
function renderCustomers(){const box=$('#customersAdmin'); if(!box)return; const p=LS.get('langar_profile',null); const cards=LS.get('langar_cards',[]); if(!p){box.innerHTML='<p class="muted">No customer registered in prototype yet.</p>';return} const level=p.orders>=30?'VIP':p.orders>=15?'Gold':p.orders>=5?'Silver':'Bronze'; box.innerHTML=`<div class="legal-block"><h3>${p.firstName} ${p.lastName||''}</h3><p>Phone: ${p.phone}<br>Email: ${p.email||'-'}<br>Birthday: ${p.birthDate||'-'}<br>QR: ${p.qr}<br>Level: <b>${level}</b></p><label>Langar Credit<input id="creditInput" value="${(p.credit||0).toFixed(2)}"></label><button id="saveCredit" class="primary">Save Credit</button><button id="sendBirthday" class="secondary">Send Birthday Card</button><button id="sendEspresso" class="secondary">Send Free Espresso Card</button></div><h3>Cards</h3><div class="cards-list">${cards.map(c=>`<article class="reward-card ${c.status}"><b>${c.title}</b><p>${c.body}</p><div class="qrbox">${c.code}</div><small>${c.status}</small></article>`).join('')}</div>`; $('#saveCredit').onclick=()=>{p.credit=parseFloat($('#creditInput').value)||0; LS.set('langar_profile',p); renderAll();}; $('#sendBirthday').onclick=()=>addCard('Birthday Reward','40% discount for birthday guest + 20% for up to 3 friends. One-time digital card.'); $('#sendEspresso').onclick=()=>addCard('Free Espresso Card','One-time free espresso card.');}
function addCard(title,body){const cards=LS.get('langar_cards',[]); cards.unshift({id:uid('card'),title,body,status:'active',code:uid('QR').toUpperCase(),unread:true,createdAt:new Date().toISOString()}); LS.set('langar_cards',cards); alert('Card sent to customer inbox/rewards.'); renderAll();}
function renderNotifications(){const box=$('#notificationsAdmin'); if(!box)return; const list=LS.get('langar_inbox',[]); box.innerHTML='<h3>Sent Inbox Messages</h3>'+list.map(x=>`<p><b>${x.title}</b><br>${x.body}<br><small>${new Date(x.createdAt).toLocaleString()}</small></p>`).join('');}
function renderGalleryAdmin(){const box=$('#galleryAdmin'); if(!box)return; const imgs=LS.get('langar_gallery',[{src:'assets/tacos_hero.jpeg',title:'Signature tacos',cat:'Tacos'},{src:'assets/prawn_tacos.jpeg',title:'Crunchy prawn tacos',cat:'Tacos'},{src:'assets/quesadilla_real.jpeg',title:'Quesadilla preview',cat:'Food'}]); box.innerHTML=imgs.map((i,idx)=>`<article><img src="${i.src}"><b>${i.title}</b><small>${i.cat||''}</small><button data-del="${idx}" class="danger">Delete</button></article>`).join(''); $$('[data-del]').forEach(b=>b.onclick=()=>{imgs.splice(+b.dataset.del,1); LS.set('langar_gallery',imgs); renderGalleryAdmin();});}
function renderAll(){renderDashboard(); renderQuickPrices(); renderMenuAdmin(); renderOrders(); renderReservations(); renderCustomers(); renderNotifications(); renderGalleryAdmin();}
$('#publishPrices')?.addEventListener('click',saveQuickPrices); $('#resetMenu')?.addEventListener('click',()=>{localStorage.removeItem('langar_menu_v3'); renderAll(); alert('Menu reset from PDF import.');}); $('#addItemBtn')?.addEventListener('click',addItem);
$('#notificationForm')?.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); const msgs=LS.get('langar_inbox',[]); msgs.unshift({id:uid('msg'),title:d.title,body:d.body,target:d.target,unread:true,createdAt:new Date().toISOString()}); LS.set('langar_inbox',msgs); e.target.reset(); renderAll(); alert('Inbox message sent.');});
$('#galleryForm')?.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); const imgs=LS.get('langar_gallery',[]); imgs.unshift(d); LS.set('langar_gallery',imgs); e.target.reset(); renderGalleryAdmin();});
renderAll();
