const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const MENU_STORAGE_KEY='langar_menu_v5';
const ICONS={
  'classic_coffee':'☕','signature_coffee':'✨☕','affogato':'🍨☕','espresso_bull':'⚡☕','coffee_cocktails':'🍸☕','tea':'🍵','tea_latte':'🫖','iced_refreshers':'🧊🍹','lemonade':'🍋','matcha':'🍵✨','smoothies':'🥭','coffee_milkshakes':'🥤☕','kids_milk':'🧸🥛','protein':'💪🥤','soft_drinks':'🧃','beer':'🍺','wine':'🍷','wine_pairing':'🧀🍷','breakfast_combos':'<span class="combo-icon">☕🥐</span>','desserts':'🧁','ice_cream':'🍦','toast_sandwiches':'🥪','tacos':'🌮','focaccia_pizza':'🍕','tapas':'<img src="assets/tapas_icon_clean.png" alt="Tapas">',
  'cat-coffee':'☕','cat-tea':'🍵','cat-matcha-smoothies':'🥤','cat-protein':'💪','cat-soft':'🧃','cat-beer-wine':'🍷','cat-combo':'<span class="combo-icon">☕🥐</span>','cat-dessert':'🧁','cat-toast':'🥖','cat-tacos':'🌮','cat-focaccia-pizza':'🍕','cat-tapas':'<img src="assets/tapas_icon_clean.png" alt="Tapas">'
};
function textOf(value, lang='en'){ if(value&&typeof value==='object') return value[lang]||value.en||value.hr||''; return value||''; }
function itemName(item, lang='en'){ return textOf(item.name, lang); }
function itemDesc(item, lang='en'){ return textOf(item.desc, lang); }
function itemIngredients(item, lang='en'){ return textOf(item.ingredients, lang) || itemDesc(item, lang); }
function setObjText(obj, lang, val){ if(!obj||typeof obj!=='object') obj={en:obj||'',hr:obj||''}; obj[lang]=val; return obj; }
function getMenu(){let m=LS.get(MENU_STORAGE_KEY,null); if(m){m=m.map(c=>({...c,icon:ICONS[c.id]||c.icon||'✦'})); LS.set(MENU_STORAGE_KEY,m); return m;} m=LANGAR_DEFAULT_MENU.map(c=>({...c,icon:ICONS[c.id]||c.icon||'✦',items:c.items.map(i=>({...i,allergens:i.allergens||(i.isAlcoholic?'18+':'ask staff')}))})); LS.set(MENU_STORAGE_KEY,m); return m;}
function saveMenu(m){LS.set(MENU_STORAGE_KEY,m)}

function uid(p){return p+'-'+Math.random().toString(36).slice(2,8)+'-'+Date.now().toString(36).slice(-4)}
function priceNum(p){const m=String(p).replace(',','.').match(/[0-9]+(\.[0-9]+)?/);return m?parseFloat(m[0]):0}
function showPanel(id){$$('.panel').forEach(p=>p.classList.toggle('hidden',p.id!==id)); renderAll();}
window.showPanel=showPanel;
function statusSelect(current){return `<select class="statusSelect"><option ${current==='new'?'selected':''}>new</option><option ${current==='accepted'?'selected':''}>accepted</option><option ${current==='preparing'?'selected':''}>preparing</option><option ${current==='ready'?'selected':''}>ready</option><option ${current==='out_for_delivery'?'selected':''}>out_for_delivery</option><option ${current==='delivered'?'selected':''}>delivered</option><option ${current==='cancelled'?'selected':''}>cancelled</option><option ${current==='rejected'?'selected':''}>rejected</option></select>`}
function renderDashboard(){const d=$('#adminDashboard'); if(!d)return; const orders=LS.get('langar_orders_v3',[]), res=LS.get('langar_reservations',[]), inbox=LS.get('langar_inbox',[]), cards=LS.get('langar_cards',[]), p=LS.get('langar_profile',null); d.innerHTML=`<button><span>🧾</span><b>${orders.length}</b><small>Orders</small></button><button><span>📅</span><b>${res.length}</b><small>Reservations</small></button><button><span>👤</span><b>${p?1:0}</b><small>Customers</small></button><button><span>🎁</span><b>${cards.filter(c=>c.status==='active').length}</b><small>Active Cards</small></button><button><span>✉</span><b>${inbox.length}</b><small>Inbox messages</small></button><button><span>🚚</span><b>${orders.filter(o=>o.status==='new').length}</b><small>New Orders</small></button>`;}
function renderQuickPrices(){const box=$('#quickPrices'); if(!box)return; const m=getMenu(); box.innerHTML=''; m.forEach(cat=>{const h=document.createElement('h3'); h.textContent=`${cat.title.en} / ${cat.title.hr}`; box.appendChild(h); cat.items.forEach(item=>{const row=document.createElement('div'); row.className='quick-price'; row.innerHTML=`<b>${itemName(item,'en')}<small>${itemName(item,'hr')}</small></b><input data-id="${item.id}" value="${item.price}"><small>${cat.title.hr}</small>`; box.appendChild(row);});});}
function saveQuickPrices(){const m=getMenu(); $$('#quickPrices input').forEach(inp=>{m.forEach(c=>c.items.forEach(i=>{if(i.id===inp.dataset.id)i.price=inp.value;}));}); saveMenu(m); alert('Prices saved and published.'); renderAll();}
function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function renderMenuAdmin(){const box=$('#menuAdmin'); if(!box)return; const m=getMenu(); box.innerHTML=''; m.forEach((cat,ci)=>{const sec=document.createElement('section'); sec.className='legal-block'; sec.innerHTML=`<h3>${cat.icon||''} ${cat.title.en} / ${cat.title.hr}</h3><label>Icon<input data-cat-icon="${cat.id}" value="${esc(cat.icon||'')}"></label><div class="table-wrap"><table class="table"><thead><tr><th>Name EN / HR</th><th>Price</th><th>Description EN / HR</th><th>Ingredients EN / HR</th><th>Active</th><th>Online</th><th>Save</th></tr></thead><tbody></tbody></table></div>`; const tbody=sec.querySelector('tbody'); cat.items.forEach((item,ii)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td><input data-f="nameEn" value="${esc(itemName(item,'en'))}"><input data-f="nameHr" value="${esc(itemName(item,'hr'))}"></td><td><input data-f="price" value="${esc(item.price)}"></td><td><textarea data-f="descEn">${esc(itemDesc(item,'en'))}</textarea><textarea data-f="descHr">${esc(itemDesc(item,'hr'))}</textarea></td><td><textarea data-f="ingEn">${esc(itemIngredients(item,'en'))}</textarea><textarea data-f="ingHr">${esc(itemIngredients(item,'hr'))}</textarea></td><td><input type="checkbox" data-f="available" ${item.available!==false?'checked':''}></td><td><input type="checkbox" data-f="orderable" ${item.orderable!==false?'checked':''}></td><td><button class="secondary saveItem">Save</button><button class="danger delItem">Del</button></td>`; tr.querySelector('.saveItem').onclick=()=>{item.name=setObjText(item.name,'en',tr.querySelector('[data-f=nameEn]').value); item.name=setObjText(item.name,'hr',tr.querySelector('[data-f=nameHr]').value); item.price=tr.querySelector('[data-f=price]').value; item.desc=setObjText(item.desc,'en',tr.querySelector('[data-f=descEn]').value); item.desc=setObjText(item.desc,'hr',tr.querySelector('[data-f=descHr]').value); item.ingredients=setObjText(item.ingredients,'en',tr.querySelector('[data-f=ingEn]').value); item.ingredients=setObjText(item.ingredients,'hr',tr.querySelector('[data-f=ingHr]').value); item.available=tr.querySelector('[data-f=available]').checked; item.orderable=tr.querySelector('[data-f=orderable]').checked; saveMenu(m); alert('Item saved/published.'); renderAll();}; tr.querySelector('.delItem').onclick=()=>{if(confirm('Delete item?')){cat.items.splice(ii,1); saveMenu(m); renderAll();}}; tbody.appendChild(tr);}); box.appendChild(sec);}); $$('[data-cat-icon]').forEach(inp=>inp.onchange=()=>{const menu=getMenu(); const c=menu.find(x=>x.id===inp.dataset.catIcon); if(c)c.icon=inp.value; saveMenu(menu); renderAll();});}
function addItem(){const m=getMenu(); const catId=prompt('Category ID (example: classic_coffee, tacos, focaccia_pizza)'); const cat=m.find(c=>c.id===catId); if(!cat)return alert('Category not found.'); const name=prompt('Item name EN'); if(!name)return; const nameHr=prompt('Item name HR', name)||name; cat.items.push({id:cat.id+'-'+(cat.items.length+1)+'-'+Date.now(),name:{en:name,hr:nameHr},desc:{hr:'Opis',en:'Description'},ingredients:{hr:'Sastojci',en:'Ingredients'},price:'€0.00',available:true,orderable:true,rewardEligible:true,allergens:'ask staff'}); saveMenu(m); renderAll();}
function renderOrders(){const box=$('#ordersAdmin'); if(!box)return; const orders=LS.get('langar_orders_v3',[]); if(!orders.length){box.innerHTML='<p class="muted">No orders yet.</p>';return} box.innerHTML=`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Paid / Complete</th></tr></thead><tbody></tbody></table>`; const tb=box.querySelector('tbody'); orders.forEach((o,idx)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td><b>${o.id}</b><br><small>${new Date(o.createdAt).toLocaleString()}</small><br>${o.type}</td><td>${o.name||'-'}<br>${o.phone||''}<br>${o.address||''}</td><td>${o.items.map(i=>`${i.qty}× ${i.nameSnapshot||itemName(i,'en')}`).join('<br>')}<br><small>${o.note||''}</small></td><td>€${(+o.total).toFixed(2)}</td><td>${statusSelect(o.status)}</td><td><label><input type="checkbox" class="paid" ${o.paid?'checked':''}> Paid</label><button class="secondary complete">Save Status</button></td>`; tr.querySelector('.complete').onclick=()=>{o.status=tr.querySelector('.statusSelect').value; o.paid=tr.querySelector('.paid').checked; if(o.status==='delivered'&&o.paid&&!o.rewardPosted){postOrderReward(o); o.rewardPosted=true;} orders[idx]=o; LS.set('langar_orders_v3',orders); alert('Order updated. Rewards posted if applicable.'); renderAll();}; tb.appendChild(tr);});}
function postOrderReward(order){let p=LS.get('langar_profile',null); if(!p)return; const firstOrder = !(p.orders||0); p.orders=(p.orders||0)+1; p.visits=(p.visits||0)+1; const credit=+(order.total*0.10).toFixed(2); p.credit=+(p.credit||0)+credit; const hist=LS.get('langar_history',[]); hist.unshift({type:'earn',text:`Order ${order.id}: €${credit.toFixed(2)} Langar Credit`,createdAt:new Date().toISOString()}); if(firstOrder && p.referredBy && !p.referralRewardPosted){p.referralRewardPosted=true; const refs=LS.get('langar_referral_rewards',[]); refs.unshift({id:uid('REFPAY'),referrerCode:p.referredBy,newCustomer:p.id,orderId:order.id,amount:0.50,status:'pending_for_cloud_or_staff_review',createdAt:new Date().toISOString()}); LS.set('langar_referral_rewards',refs); hist.unshift({type:'referral',text:`Referral ${p.referredBy}: €0.50 reward should be posted to referrer after cloud verification.`,createdAt:new Date().toISOString()});} LS.set('langar_profile',p); LS.set('langar_history',hist);}
function renderReservations(){const box=$('#reservationsAdmin'); if(!box)return; const arr=LS.get('langar_reservations',[]); if(!arr.length){box.innerHTML='<p class="muted">No reservations yet.</p>';return} box.innerHTML=`<table class="table"><thead><tr><th>Date/Time</th><th>Customer</th><th>Guests</th><th>Note</th><th>Status</th></tr></thead><tbody></tbody></table>`; const tb=box.querySelector('tbody'); arr.forEach((r,idx)=>{const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.date}<br>${r.time}</td><td>${r.name}<br>${r.phone}</td><td>${r.guests}</td><td>${r.note||''}</td><td><select><option ${r.status==='pending'?'selected':''}>pending</option><option ${r.status==='confirmed'?'selected':''}>confirmed</option><option ${r.status==='cancelled'?'selected':''}>cancelled</option><option ${r.status==='completed'?'selected':''}>completed</option></select><button class="secondary">Save</button></td>`; tr.querySelector('button').onclick=()=>{r.status=tr.querySelector('select').value; arr[idx]=r; LS.set('langar_reservations',arr); renderReservations();}; tb.appendChild(tr);});}
function renderCustomers(){const box=$('#customersAdmin'); if(!box)return; const p=LS.get('langar_profile',null); const cards=LS.get('langar_cards',[]); if(!p){box.innerHTML='<p class="muted">No customer registered in prototype yet.</p>';return} const level=p.orders>=30?'VIP':p.orders>=15?'Gold':p.orders>=5?'Silver':'Bronze'; box.innerHTML=`<div class="legal-block"><h3>${p.firstName} ${p.lastName||''}</h3><p>Phone: ${p.phone}<br>Email: ${p.email||'-'}<br>Birthday: ${p.birthDate||'-'}<br>QR: ${p.qr}<br>Level: <b>${level}</b></p><label>Langar Credit<input id="creditInput" value="${(p.credit||0).toFixed(2)}"></label><button id="saveCredit" class="primary">Save Credit</button><button id="sendBirthday" class="secondary">Send Birthday Card</button><button id="sendEspresso" class="secondary">Send Free Espresso Card</button></div><h3>Cards</h3><div class="cards-list">${cards.map(c=>`<article class="reward-card ${c.status}"><b>${c.title}</b><p>${c.body}</p><div class="qrbox">${c.code}</div><small>${c.status}</small></article>`).join('')}</div>`; $('#saveCredit').onclick=()=>{p.credit=parseFloat($('#creditInput').value)||0; LS.set('langar_profile',p); renderAll();}; $('#sendBirthday').onclick=()=>addCard('Birthday Reward','40% discount for birthday guest + 20% for up to 3 friends. One-time digital card.'); $('#sendEspresso').onclick=()=>addCard('Free Espresso Card','One-time free espresso card.');}
function addCard(title,body){const cards=LS.get('langar_cards',[]); cards.unshift({id:uid('card'),title,body,status:'active',code:uid('QR').toUpperCase(),unread:true,createdAt:new Date().toISOString()}); LS.set('langar_cards',cards); alert('Card sent to customer inbox/rewards.'); renderAll();}
function renderNotifications(){const box=$('#notificationsAdmin'); if(!box)return; const list=LS.get('langar_inbox',[]); box.innerHTML='<h3>Sent Inbox Messages</h3>'+list.map(x=>`<p><b>${x.title}</b><br>${x.body}<br><small>${new Date(x.createdAt).toLocaleString()}</small></p>`).join('');}
function renderGalleryAdmin(){const box=$('#galleryAdmin'); if(!box)return; const imgs=LS.get('langar_gallery',[{src:'assets/tacos_hero.jpeg',title:'Signature tacos',cat:'Tacos'},{src:'assets/prawn_tacos.jpeg',title:'Crunchy prawn tacos',cat:'Tacos'},{src:'assets/quesadilla_real.jpeg',title:'Quesadilla preview',cat:'Food'}]); box.innerHTML=imgs.map((i,idx)=>`<article><img src="${i.src}"><b>${i.title}</b><small>${i.cat||''}</small><button data-del="${idx}" class="danger">Delete</button></article>`).join(''); $$('[data-del]').forEach(b=>b.onclick=()=>{imgs.splice(+b.dataset.del,1); LS.set('langar_gallery',imgs); renderGalleryAdmin();});}
function renderReferralAdmin(){const box=$('#referralsAdmin'); if(!box)return; const refs=LS.get('langar_referral_rewards',[]); if(!refs.length){box.innerHTML='<p class="muted">No referral rewards posted yet.</p>';return;} box.innerHTML=`<table class="table"><thead><tr><th>Referrer Code</th><th>New Customer</th><th>Order</th><th>Amount</th><th>Status</th></tr></thead><tbody>${refs.map(r=>`<tr><td>${r.referrerCode}</td><td>${r.newCustomer}</td><td>${r.orderId}</td><td>€${(+r.amount).toFixed(2)}</td><td>${r.status}</td></tr>`).join('')}</tbody></table>`;}

function renderFeedbackAdmin(){const box=$('#feedbackAdmin'); if(!box)return; const list=LS.get('langar_feedback',[]); if(!list.length){box.innerHTML='<p class="muted">No feedback yet.</p>';return;} const pub=list.filter(f=>+f.rating>=4), neg=list.filter(f=>+f.rating<4); box.innerHTML=`<h3>Public positive reviews</h3>${pub.length?`<table class="table"><tbody>${pub.map(f=>`<tr><td>${'★'.repeat(+f.rating)}</td><td><b>${f.name||'Guest'}</b><br>${f.message}<br><small>${f.favorite||''}</small></td><td>${new Date(f.createdAt).toLocaleString()}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">No public reviews yet.</p>'}<h3>Admin-only negative / neutral feedback</h3>${neg.length?`<table class="table"><tbody>${neg.map(f=>`<tr><td>${'★'.repeat(+f.rating)}</td><td><b>${f.name||'Guest'}</b><br>${f.message}<br><small>${f.favorite||''}</small></td><td>${new Date(f.createdAt).toLocaleString()}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">No admin-only problems yet.</p>'}`;}
function setupExperienceForms(){const daily=$('#dailyForm'); if(daily&&!daily.dataset.ready){daily.dataset.ready='1'; const d=LS.get('langar_daily_surprise',{title:{en:'Today’s Surprise',hr:'Današnje iznenađenje'},body:{en:'Join Langar Club and watch for opening offers.',hr:'Pridružite se Langar Clubu i pratite posebne ponude za otvorenje.'}}); daily.titleEn.value=d.title.en||''; daily.titleHr.value=d.title.hr||''; daily.bodyEn.value=d.body.en||''; daily.bodyHr.value=d.body.hr||''; daily.onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(daily).entries()); LS.set('langar_daily_surprise',{title:{en:data.titleEn,hr:data.titleHr},body:{en:data.bodyEn,hr:data.bodyHr}}); alert('Daily Surprise saved.');};} const poll=$('#pollForm'); if(poll&&!poll.dataset.ready){poll.dataset.ready='1'; const po=LS.get('langar_poll',{question:{en:'Which flavor should come next?',hr:'Koji okus želite sljedeći?'},options:['Pistachio Protein','Mango Ice Cream','Spicy Taco','Chocolate Dessert'],votes:{}}); poll.qEn.value=po.question.en||''; poll.qHr.value=po.question.hr||''; poll.options.value=(po.options||[]).join('\n'); poll.onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(poll).entries()); LS.set('langar_poll',{question:{en:data.qEn,hr:data.qHr},options:data.options.split('\n').map(x=>x.trim()).filter(Boolean),votes:{}}); alert('Poll saved and votes reset.');};}}
function renderAll(){renderDashboard(); renderQuickPrices(); renderMenuAdmin(); renderOrders(); renderReservations(); renderCustomers(); renderReferralAdmin(); renderNotifications(); renderFeedbackAdmin(); setupExperienceForms(); renderGalleryAdmin();}
$('#publishPrices')?.addEventListener('click',saveQuickPrices); $('#resetMenu')?.addEventListener('click',()=>{localStorage.removeItem(MENU_STORAGE_KEY); localStorage.removeItem('langar_menu_v3'); renderAll(); alert('Menu reset from PDF import.');}); $('#addItemBtn')?.addEventListener('click',addItem);
$('#notificationForm')?.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); const msgs=LS.get('langar_inbox',[]); msgs.unshift({id:uid('msg'),title:d.title,body:d.body,target:d.target,unread:true,createdAt:new Date().toISOString()}); LS.set('langar_inbox',msgs); e.target.reset(); renderAll(); alert('Inbox message sent.');});
$('#galleryForm')?.addEventListener('submit',e=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.target).entries()); const imgs=LS.get('langar_gallery',[]); imgs.unshift(d); LS.set('langar_gallery',imgs); e.target.reset(); renderGalleryAdmin();});
renderAll();
