(() => {
  'use strict';
  const VERSION='6.0.9';
  const ZAGREB='Europe/Zagreb';
  const printLock=new Map();
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>`€${(Number(v)||0).toFixed(2)}`;
  const client=()=>window.LangarAdminCloud?.client||null;
  const asItems=v=>Array.isArray(v)?v:(()=>{try{return JSON.parse(v||'[]')}catch{return []}})();
  const localDayKey=d=>{try{const p=new Intl.DateTimeFormat('en-CA',{timeZone:ZAGREB,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}catch{return new Date(d).toISOString().slice(0,10)}};
  const localDate=(key,time='00:00:00')=>new Date(`${key}T${time}`);
  const todayKey=()=>localDayKey(new Date());
  const addDays=(key,n)=>{const d=localDate(key,'12:00:00');d.setDate(d.getDate()+n);return localDayKey(d)};
  const monthStart=key=>key.slice(0,8)+'01';
  const weekStart=key=>{const d=localDate(key,'12:00:00');const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return localDayKey(d)};

  function boot(){document.body.classList.add('v609-enhanced');installButtonColorObserver();installOrderPrintGuard();installReports();installMenuTools();installDiagnostics();decorateVersion()}
  function decorateVersion(){const span=document.querySelector('.topbar .brand span');if(span&&!span.textContent.includes('6.0.9'))span.textContent=`V${VERSION} Admin Test`}

  function rgb(s){const m=String(s||'').match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/i);return m?[+m[1],+m[2],+m[3]]:null}
  function lum(c){if(!c)return .5;return (0.2126*c[0]+0.7152*c[1]+0.0722*c[2])/255}
  function isGreen(c){return !!c&&c[1]>c[0]*1.15&&c[1]>c[2]*1.05&&c[1]>45}
  function colorButtons(root=document){$$('button,a.secondary,a.primary',root).forEach(el=>{if(el.classList.contains('danger')||el.closest('.danger'))return;el.classList.remove('v609-btn-white','v609-btn-green');const cs=getComputedStyle(el),bg=rgb(cs.backgroundColor);if(bg&&lum(bg)>.78)el.classList.add('v609-btn-white');else if(bg&&isGreen(bg))el.classList.add('v609-btn-green')})}
  function installButtonColorObserver(){colorButtons();const mo=new MutationObserver(ms=>{for(const m of ms)m.addedNodes.forEach(n=>{if(n.nodeType===1)colorButtons(n)})});mo.observe(document.documentElement,{subtree:true,childList:true});setInterval(colorButtons,4000)}

  function orderCache(id){return window.LANGAR_ADMIN_ORDER_CACHE?.[String(id)]||null}
  function orderTypeLabel(t){const x=String(t||'pickup').toLowerCase().replace(/[- ]/g,'_');return ['dine_in','dinein','table','inside'].includes(x)?'DINE-IN':x==='delivery'?'DELIVERY':'PICK-UP'}
  function itemLabel(i){return i.name_hr||i.name_en||i.nameSnapshotHr||i.nameSnapshot||i.name||i.sku||i.id||'Item'}
  function printHtml(o,copyType){const items=asItems(o.items),title=copyType==='delivery'?`${orderTypeLabel(o.fulfillment_type)} COPY`:'KITCHEN / INTERNAL TICKET';const lines=items.map(i=>{const add=Array.isArray(i.addOns)&&i.addOns.length?`<div class="addons">+ ${esc(i.addOns.map(a=>a.name||a.name_hr||a.name_en||a.id).join(', '))}</div>`:'',note=i.note?`<div class="note">NOTE: ${esc(i.note)}</div>`:'';return `<div class="item"><div class="item-main"><b>${esc(i.qty||1)} × ${esc(itemLabel(i))}</b><b>${money(i.line_total??((i.qty||1)*(i.price||0)))}</b></div>${add}${note}</div>`}).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(o.order_number||'Langar Ticket')}</title><style>@page{size:80mm auto;margin:2.5mm}*{box-sizing:border-box}body{width:74mm;margin:0 auto;font-family:Arial,Helvetica,sans-serif;color:#000;background:#fff;font-size:13px;font-weight:700;line-height:1.28}.center{text-align:center}.brand{font-size:19px;font-weight:900}.type{font-size:17px;border:2px solid #000;padding:4px;margin:5px 0;font-weight:900}.order{font-size:22px;font-weight:900;margin:5px 0}.meta{font-size:12px;margin:3px 0}.rule{border-top:2px dashed #000;margin:7px 0}.item{padding:7px 0;border-bottom:1px dashed #000}.item-main{display:flex;justify-content:space-between;gap:7px;font-size:14px}.item-main b:first-child{flex:1}.addons{font-size:12px;margin-top:3px}.note{font-size:13px;margin-top:4px;border:2px solid #000;padding:4px;font-weight:900}.order-note{border:3px solid #000;padding:6px;font-size:14px;font-weight:900;margin:7px 0}.total{display:flex;justify-content:space-between;font-size:18px;font-weight:900;margin-top:7px}.nf{font-size:11px;margin-top:8px;font-weight:900}.address{font-size:13px;font-weight:900;margin:5px 0}.footer{font-size:10px;margin-top:6px}</style></head><body><div class="center brand">LANGAR BAR</div><div class="center type">${title}</div><div class="center order">${esc(o.order_number||String(o.id).slice(0,8))}</div><div class="center meta">${new Date(o.created_at||Date.now()).toLocaleString()}</div><div class="center meta">${orderTypeLabel(o.fulfillment_type)}${o.table_number?` · TABLE ${esc(o.table_number)}`:''}</div>${o.customer_name?`<div class="meta">NAME: ${esc(o.customer_name)}</div>`:''}${o.customer_phone?`<div class="meta">PHONE: ${esc(o.customer_phone)}</div>`:''}${o.delivery_address?`<div class="address">ADDRESS: ${esc(o.delivery_address)}</div>`:''}<div class="rule"></div>${lines||'<div>No items</div>'}${o.note?`<div class="order-note">ORDER NOTE: ${esc(o.note)}</div>`:''}<div class="total"><span>TOTAL</span><span>${money(o.total)}</span></div><div class="center nf">INTERNAL / NON-FISCAL TICKET — NOT A TAX INVOICE</div><div class="center footer">Langar Admin V${VERSION}</div></body></html>`}
  async function auditPrint(id,type){try{const c=client();if(!c)return;await c.rpc('admin_record_order_print_v609',{p_order_id:id,p_copy_type:type,p_device_label:(navigator.userAgent||'').slice(0,150),p_metadata:{source:'admin-v609',screen:`${innerWidth}x${innerHeight}`}})}catch(e){console.warn('[V609] print audit failed',e?.message||e)}}
  async function doPrint(id,type,button){const key=`${id}:${type}`,now=Date.now();if((printLock.get(key)||0)>now-4000)return;printLock.set(key,now);const o=orderCache(id);if(!o){alert('Order data is not loaded yet. Refresh Orders and try again.');return}if(button){button.disabled=true;setTimeout(()=>button.disabled=false,4000)}const w=window.open('','_blank','width=480,height=720');if(!w){alert('Pop-up blocked. Allow pop-ups for this admin page and try again.');return}w.document.open();w.document.write(printHtml(o,type));w.document.close();await auditPrint(id,type);setTimeout(()=>{try{w.focus();w.print()}catch{}},180)}
  function installOrderPrintGuard(){document.addEventListener('click',e=>{const b=e.target.closest('[data-print-order],[data-print-delivery]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const id=b.dataset.printOrder||b.dataset.printDelivery,type=b.dataset.printDelivery?'delivery':'internal';doPrint(id,type,b)},true)}

  async function fetchOrdersRange(startKey,endExclusiveKey){const c=client();if(!c)throw new Error('Cloud Admin client is not available. Login first.');const from=localDate(startKey).toISOString(),to=localDate(endExclusiveKey).toISOString(),out=[];let a=0;const page=500;while(true){const {data,error}=await c.from('customer_orders').select('*').gte('created_at',from).lt('created_at',to).order('created_at',{ascending:false}).range(a,a+page-1);if(error)throw error;out.push(...(data||[]));if(!data||data.length<page)break;a+=page;if(a>10000)break}return out.filter(o=>!o.is_test)}
  function reportSummary(rows){const completed=rows.filter(o=>String(o.status).toLowerCase()==='completed'),cancelled=rows.filter(o=>['cancelled','rejected'].includes(String(o.status).toLowerCase())),paid=rows.filter(o=>o.paid===true),allTotal=rows.reduce((s,o)=>s+Number(o.total||0),0),realized=rows.filter(o=>o.paid&&String(o.status).toLowerCase()==='completed').reduce((s,o)=>s+Number(o.total||0),0),avg=rows.length?allTotal/rows.length:0,delivery=rows.reduce((s,o)=>s+Number(o.delivery_fee||0),0),discounts=rows.reduce((s,o)=>s+Number(o.discount_total||0),0);return {completed,cancelled,paid,allTotal,realized,avg,delivery,discounts}}
  function renderReport(rows,start,end){const box=$('#v609ReportResult');if(!box)return;const s=reportSummary(rows),statusCounts={},typeCounts={};rows.forEach(o=>{statusCounts[o.status]=(statusCounts[o.status]||0)+1;const t=orderTypeLabel(o.fulfillment_type);typeCounts[t]=(typeCounts[t]||0)+1});box.innerHTML=`<div class="v609-summary"><div class="v609-report-stat"><small>Orders</small><b>${rows.length}</b></div><div class="v609-report-stat"><small>Completed</small><b>${s.completed.length}</b></div><div class="v609-report-stat"><small>Cancelled / rejected</small><b>${s.cancelled.length}</b></div><div class="v609-report-stat"><small>Paid</small><b>${s.paid.length}</b></div><div class="v609-report-stat"><small>All order value</small><b>${money(s.allTotal)}</b></div><div class="v609-report-stat"><small>Completed + paid</small><b>${money(s.realized)}</b></div><div class="v609-report-stat"><small>Average order</small><b>${money(s.avg)}</b></div><div class="v609-report-stat"><small>Delivery / discounts</small><b>${money(s.delivery)} / ${money(s.discounts)}</b></div></div><p class="v609-report-note"><b>Period:</b> ${esc(start)} to ${esc(addDays(end,-1))} · <b>Status:</b> ${esc(Object.entries(statusCounts).map(([k,v])=>`${k}: ${v}`).join(' · ')||'—')} · <b>Type:</b> ${esc(Object.entries(typeCounts).map(([k,v])=>`${k}: ${v}`).join(' · ')||'—')}</p><div class="v609-report-table-wrap"><table class="v609-report-table"><thead><tr><th>Date</th><th>Order</th><th>Type</th><th>Status</th><th>Paid</th><th>Customer</th><th>Items</th><th>Total</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(new Date(o.created_at).toLocaleString())}</td><td><b>${esc(o.order_number||String(o.id).slice(0,8))}</b></td><td>${orderTypeLabel(o.fulfillment_type)}</td><td>${esc(o.status)}</td><td>${o.paid?'YES':'NO'}</td><td>${esc(o.customer_name||'')}${o.customer_phone?`<br>${esc(o.customer_phone)}`:''}</td><td>${asItems(o.items).map(i=>`${esc(i.qty||1)}× ${esc(itemLabel(i))}`).join('<br>')}</td><td><b>${money(o.total)}</b></td></tr>`).join('')}</tbody></table></div>`;window.__V609_REPORT={rows,start,end}}
  function csvCell(v){const s=String(v??'');return `"${s.replace(/"/g,'""')}"`}
  function exportCsv(){const r=window.__V609_REPORT;if(!r)return alert('Run report first.');const rows=[['Date','Order','Type','Status','Paid','Customer','Phone','Items','Total EUR']];r.rows.forEach(o=>rows.push([new Date(o.created_at).toLocaleString(),o.order_number||o.id,orderTypeLabel(o.fulfillment_type),o.status,o.paid?'YES':'NO',o.customer_name||'',o.customer_phone||'',asItems(o.items).map(i=>`${i.qty||1}x ${itemLabel(i)}`).join(' | '),Number(o.total||0).toFixed(2)]));const blob=new Blob(['\ufeff'+rows.map(x=>x.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`langar-internal-orders-${r.start}-to-${addDays(r.end,-1)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function printA4(){const r=window.__V609_REPORT;if(!r)return alert('Run report first.');const s=reportSummary(r.rows),w=open('','_blank');if(!w)return alert('Allow pop-ups first.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Langar internal report</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#111}h1{margin:0}.nf{border:2px solid #111;padding:8px;font-weight:bold;margin:10px 0}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.summary div{border:1px solid #aaa;padding:7px}table{width:100%;border-collapse:collapse;font-size:10px;margin-top:10px}th,td{border:1px solid #bbb;padding:4px;text-align:left;vertical-align:top}th{background:#eee}</style></head><body><h1>Langar Bar — Internal Order Report</h1><p>${esc(r.start)} to ${esc(addDays(r.end,-1))}</p><div class="nf">NON-FISCAL INTERNAL REPORT — NOT A TAX RETURN OR FISCAL INVOICE</div><div class="summary"><div>Orders<br><b>${r.rows.length}</b></div><div>Completed<br><b>${s.completed.length}</b></div><div>All value<br><b>${money(s.allTotal)}</b></div><div>Completed + paid<br><b>${money(s.realized)}</b></div></div><table><thead><tr><th>Date</th><th>Order</th><th>Type</th><th>Status</th><th>Paid</th><th>Items</th><th>Total</th></tr></thead><tbody>${r.rows.map(o=>`<tr><td>${esc(new Date(o.created_at).toLocaleString())}</td><td>${esc(o.order_number||o.id)}</td><td>${orderTypeLabel(o.fulfillment_type)}</td><td>${esc(o.status)}</td><td>${o.paid?'YES':'NO'}</td><td>${asItems(o.items).map(i=>`${esc(i.qty||1)}× ${esc(itemLabel(i))}`).join('<br>')}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></body></html>`);w.document.close();setTimeout(()=>w.print(),200)}
  async function runReport(){const start=$('#v609Start')?.value,endInclusive=$('#v609End')?.value;if(!start||!endInclusive)return alert('Choose start and end date.');if(endInclusive<start)return alert('End date must be after start date.');const end=addDays(endInclusive,1),st=$('#v609ReportStatus');if(st)st.textContent='Loading orders from Supabase...';try{const rows=await fetchOrdersRange(start,end);renderReport(rows,start,end);if(st)st.textContent=`Loaded ${rows.length} real order(s). Test orders excluded.`}catch(e){if(st)st.textContent='Report error: '+(e.message||e)}}
  function setPeriod(kind){const t=todayKey();let s=t,e=t;if(kind==='week')s=weekStart(t);else if(kind==='month')s=monthStart(t);$('#v609Start').value=s;$('#v609End').value=e;runReport()}
  function installReports(){const panel=$('#ordersPanel');if(!panel||$('#v609Reports'))return;const el=document.createElement('section');el.id='v609Reports';el.className='v609-report-card';el.innerHTML=`<h3>📊 Internal Sales & Order Reports — V${VERSION}</h3><p class="v609-report-note">Daily, weekly, monthly or custom period. Test orders are excluded. This is an internal operational report and does not replace the Croatian fiscal system.</p><div class="v609-periods"><button type="button" class="secondary" data-v609-period="today">Today</button><button type="button" class="secondary" data-v609-period="week">This week</button><button type="button" class="secondary" data-v609-period="month">This month</button></div><div class="v609-report-toolbar"><label>From<input id="v609Start" type="date" value="${todayKey()}"></label><label>To<input id="v609End" type="date" value="${todayKey()}"></label><button type="button" id="v609RunReport" class="primary">Run report</button><button type="button" id="v609PrintA4" class="secondary">Print A4</button><button type="button" id="v609ExportCsv" class="secondary">Export CSV</button></div><div id="v609ReportStatus" class="v609-report-status">Ready.</div><div id="v609ReportResult"></div>`;const head=panel.querySelector('.section-head');(head||panel).insertAdjacentElement('afterend',el);$('#v609RunReport').onclick=runReport;$('#v609PrintA4').onclick=printA4;$('#v609ExportCsv').onclick=exportCsv;$$('[data-v609-period]').forEach(b=>b.onclick=()=>setPeriod(b.dataset.v609Period))}

  function normalizePriceInput(inp){const raw=String(inp.value||'').trim().replace(',','.');if(raw==='')return true;const n=Number(raw);if(!Number.isFinite(n)||n<0){inp.setCustomValidity('Enter a valid non-negative price.');return false}inp.value=n.toFixed(2);inp.setCustomValidity('');return true}
  function filterMenu(q){q=String(q||'').trim().toLowerCase();let shown=0;$$('#menuAdmin tr,#menuAdmin .menu-item-row,#menuAdmin article').forEach(row=>{if(row.closest('thead'))return;const ok=!q||row.textContent.toLowerCase().includes(q);row.style.display=ok?'':'none';if(ok)shown++});const c=$('#v609MenuCount');if(c)c.textContent=`${shown} visible row(s)`}
  function installMenuTools(){const panel=$('#menuPanel');if(!panel||$('#v609MenuTools'))return;const box=document.createElement('div');box.id='v609MenuTools';box.className='v609-menu-tools';box.innerHTML=`<b>Fast Menu Tools — V${VERSION}</b><div class="toolbar"><input id="v609MenuSearch" type="search" placeholder="Search item, SKU or category"><button type="button" id="v609ClearSearch" class="secondary">Clear search</button><span id="v609MenuCount" class="muted"></span></div><div class="v609-pack-box"><b>Sales Pack helper</b><p class="muted">Use this to prepare the title and price of a bundle quickly, then add it through “Add Item” so the existing menu workflow remains compatible.</p><div class="v609-pack-grid"><label>Pack name EN<input id="v609PackEn" placeholder="Coffee + Cake Pack"></label><label>Pack name HR<input id="v609PackHr" placeholder="Kava + kolač paket"></label><label>Pack price<input id="v609PackPrice" inputmode="decimal" placeholder="7.90"></label><label>Pack note<input id="v609PackNote" placeholder="Espresso + selected cake"></label></div><button type="button" id="v609PackPreviewBtn" class="secondary">Preview pack</button><div id="v609PackPreview" class="v609-pack-preview" hidden></div></div>`;const target=panel.querySelector('.toolbar');(target||panel.querySelector('.section-head')||panel).insertAdjacentElement('afterend',box);$('#v609MenuSearch').oninput=e=>filterMenu(e.target.value);$('#v609ClearSearch').onclick=()=>{$('#v609MenuSearch').value='';filterMenu('')};$('#v609PackPrice').onblur=e=>normalizePriceInput(e.target);$('#v609PackPreviewBtn').onclick=()=>{const p=$('#v609PackPreview'),price=String($('#v609PackPrice').value||'').replace(',','.'),n=Number(price);p.hidden=false;p.innerHTML=`<b>${esc($('#v609PackEn').value||'Sales Pack')}</b><br>${esc($('#v609PackHr').value||'')}<br><strong>${Number.isFinite(n)?money(n):'Set a valid price'}</strong><br><small>${esc($('#v609PackNote').value||'')}</small>`};document.addEventListener('input',e=>{if(e.target.closest('#menuAdmin')&&e.target.matches('input,textarea,select')){e.target.closest('tr,article,.menu-item-row')?.classList.add('v609-unsaved');if(/price/i.test(e.target.name||e.target.dataset?.field||e.target.placeholder||''))normalizePriceInput(e.target)}});document.addEventListener('click',e=>{const b=e.target.closest('#menuPanel button');if(!b)return;if(!/save|publish/i.test(b.textContent||b.id||''))b.type='button'},true)}

  function installDiagnostics(){setTimeout(()=>{const bad=[];$$('[onclick*="showPanel"]').forEach(b=>{const m=String(b.getAttribute('onclick')).match(/showPanel\(['\"]([^'\"]+)/);if(m&&!document.getElementById(m[1]))bad.push(`${b.textContent.trim()} → ${m[1]}`)});const panel=$('#settingsPanel');if(panel&&!$('#v609Diagnostics')){const d=document.createElement('div');d.id='v609Diagnostics';d.className='legal-block v609-diagnostic';d.innerHTML=`<b>V${VERSION} diagnostics</b><p>${bad.length?`Missing panel targets: ${esc(bad.join(' | '))}`:'✓ Admin navigation targets checked: no missing inline panel targets detected.'}</p><p>✓ Print guard active · ✓ Report tools active · ✓ Readable order ticket style active · ✓ Button contrast observer active.</p>`;panel.appendChild(d)}},1200)}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
