(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const lang=()=>localStorage.langar_lang||'hr'; const t=(hr,en)=>lang()==='hr'?hr:en;
function installId(){let id=localStorage.langar_install_id_v500;if(!id){id=(crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.langar_install_id_v500=id;}return id;}
function addToggle(input){if(!input||input.dataset.toggleReady)return;input.dataset.toggleReady='1';const w=document.createElement('div');w.className='password-field-v500';input.parentNode.insertBefore(w,input);w.appendChild(input);const b=document.createElement('button');b.type='button';b.className='password-toggle-v500';b.setAttribute('aria-label',t('Prikaži lozinku','Show password'));b.textContent='👁';b.onclick=()=>{input.type=input.type==='password'?'text':'password';b.textContent=input.type==='password'?'👁':'🙈';};w.appendChild(b);}
function score(p){let s=0;if(p.length>=8)s++;if(/[a-z]/.test(p)&&/[A-Z]/.test(p))s++;if(/\d/.test(p))s++;if(/[^A-Za-z0-9]/.test(p))s++;return s;}
function enhancePasswords(){ $$('input[type="password"]').forEach(addToggle); const p=$('#clubForm input[name="password"]'); if(p&&!p.dataset.strengthReady){p.dataset.strengthReady='1';const m=document.createElement('small');m.className='password-strength-v500';p.closest('label')?.appendChild(m);p.addEventListener('input',()=>{const s=score(p.value);m.textContent=[t('Vrlo slaba','Very weak'),t('Slaba','Weak'),t('Dobra','Good'),t('Jaka','Strong'),t('Vrlo jaka','Very strong')][s];m.dataset.score=s;});}}
function addForgot(){const f=$('#clubLoginForm');if(!f||$('#forgotPasswordV500'))return;const b=document.createElement('button');b.type='button';b.id='forgotPasswordV500';b.className='link-button-v500';b.textContent=t('Zaboravili ste lozinku?','Forgot password?');b.onclick=async()=>{const email=String(f.querySelector('[name="loginEmail"]')?.value||prompt(t('Unesite email','Enter your email'))||'').trim();if(!email)return;const c=window.LangarCloud?.client;if(!c)return alert(t('Cloud nije dostupan.','Cloud is unavailable.'));const redirectTo=new URL('index.html?reset=1',location.href).href;const {error}=await c.auth.resetPasswordForEmail(email,{redirectTo});alert(error?error.message:t('Poslali smo poveznicu za promjenu lozinke. Provjerite Inbox i Spam.','Password reset link sent. Check Inbox and Spam.'));};f.appendChild(b);}
async function handleRecovery(){const c=window.LangarCloud?.client;if(!c)return;c.auth.onAuthStateChange(async(event)=>{if(event!=='PASSWORD_RECOVERY')return;const p=prompt(t('Unesite novu lozinku (najmanje 8 znakova)','Enter a new password (at least 8 characters)'));if(!p)return;if(score(p)<3)return alert(t('Lozinka mora biti jača: veliko/malo slovo, broj i poseban znak.','Use a stronger password with upper/lowercase letters, a number, and a symbol.'));const {error}=await c.auth.updateUser({password:p});alert(error?error.message:t('Lozinka je uspješno promijenjena.','Password changed successfully.'));history.replaceState({},'',location.pathname);});}
function enforceStrongSignup(){const f=$('#clubForm');if(!f||f.dataset.strongReady)return;f.dataset.strongReady='1';f.addEventListener('submit',e=>{const p=String(f.querySelector('[name="password"]')?.value||'');if(p.length<8||score(p)<3){e.preventDefault();e.stopImmediatePropagation();alert(t('Lozinka mora imati najmanje 8 znakova te veliko/malo slovo, broj i poseban znak.','Password must be at least 8 characters and include upper/lowercase letters, a number, and a symbol.'));}},true);}function legalLinks(){const terms=$('#clubForm [name="terms"]')?.closest('label');if(terms&&!terms.dataset.legalReady){terms.dataset.legalReady='1';const s=terms.querySelector('span');if(s)s.innerHTML=t('Prihvaćam <a href="terms.html" target="_blank">Uvjete korištenja</a> i <a href="privacy.html" target="_blank">Pravila privatnosti</a>.','I accept the <a href="terms.html" target="_blank">Terms of Use</a> and <a href="privacy.html" target="_blank">Privacy Policy</a>.');}}
async function secureWelcomeClaim(){const c=window.LangarCloud?.client;if(!c)return;const {data:{session}}=await c.auth.getSession();if(!session)return;const p=JSON.parse(localStorage.langar_profile||'{}');if(!p.phone)return;try{await c.rpc('claim_welcome_espresso_v500',{p_phone:p.phone,p_install_id:installId()});}catch(e){console.warn('Welcome claim unavailable',e);} }
function disableUnsafeLocalRedeem(){document.addEventListener('click',e=>{const b=e.target.closest?.('[onclick*="redeemCard"]');if(!b)return;const id=(b.getAttribute('onclick')||'').match(/redeemCard\(['\"]([^'\"]+)/)?.[1];const card=(JSON.parse(localStorage.langar_cards||'[]')).find(x=>x.id===id);if(card?.cloudId){e.preventDefault();e.stopImmediatePropagation();alert(t('Karticu mora skenirati i potvrditi osoblje Langar Bara.','This card must be scanned and redeemed by Langar Bar staff.'));}},true);}
function boot(){enhancePasswords();addForgot();enforceStrongSignup();legalLinks();handleRecovery();disableUnsafeLocalRedeem();setTimeout(secureWelcomeClaim,1800);new MutationObserver(()=>{enhancePasswords();addForgot();enforceStrongSignup();legalLinks();}).observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
