(()=>{
'use strict';
let lastState='';
async function refreshCloudMenu(){try{if(window.LangarCloudV42?.refreshCloudData)await window.LangarCloudV42.refreshCloudData()}catch(e){console.warn('[V611] menu refresh',e?.message||e)}}
function installCloudGuards(){const mod=window.LangarOrderCloud;if(!mod||mod.__v611)return false;
  if(typeof mod.submitOrder==='function'){const original=mod.submitOrder.bind(mod);mod.submitOrder=async order=>{await refreshCloudMenu();try{return await original(order)}catch(e){const m=String(e?.message||e);if(/price|total mismatch|unavailable|orderable|menu/i.test(m)){await refreshCloudMenu();return await original(order)}throw e}}}
  mod.requestOrderCancellation=async(token,reason='',note='')=>{if(!token)throw new Error('Missing order tracking token.');const c=window.LangarCloud?.client||mod.client;if(!c)throw new Error('Cloud connection is not available.');const reasonCode=String(reason||'').trim(),reasonNote=String(note||'').trim();let r=await c.rpc('request_order_cancellation_v459',{p_token:token,p_reason_code:reasonCode||null,p_reason_note:reasonNote||null});if(r.error&&String(r.error.message||'').toLowerCase().includes('request_order_cancellation_v459')){r=await c.rpc('request_order_cancellation_by_token',{p_token:token,p_reason:[reasonCode,reasonNote].filter(Boolean).join(' — ')||null})}if(r.error)throw r.error;const {data:check,error:checkErr}=await c.rpc('get_customer_order_by_token',{p_token:token});if(checkErr)throw checkErr;const row=Array.isArray(check)?check[0]:check;if(!row?.cancel_requested_at||String(row.cancel_status||'requested')!=='requested')throw new Error('Cancellation request was not confirmed by Cloud. Please retry.');setTimeout(()=>sync(),200);return row};
  mod.__v611=true;return true}
async function sync(){try{if(window.LangarOrderCloud?.syncAccountOrders){const r=await window.LangarOrderCloud.syncAccountOrders(120);if(r?.changed&&typeof window.renderCustomerOrderStatus==='function')window.renderCustomerOrderStatus()}else if(typeof window.syncCustomerOrderStatuses==='function')await window.syncCustomerOrderStatuses();notifyChange()}catch(e){console.warn('[V611] order sync',e?.message||e)}}
function orders(){try{const uid=localStorage.langar_current_user_id;const keys=uid?[`langar_orders_user_${uid}`]:['langar_orders_guest','langar_orders_v3'];for(const k of keys){const a=JSON.parse(localStorage.getItem(k)||'[]');if(Array.isArray(a)&&a.length)return a}return []}catch{return []}}
function notifyChange(){const a=orders();const active=a.find(o=>!['completed','cancelled','rejected'].includes(String(o.status||'').toLowerCase()));if(!active)return;const sig=[active.cloudId||active.id,active.status,active.estimatedReadyAt||active.estimated_ready_at,active.estimatedMinutes||active.estimated_minutes,active.cancelRequestedAt||active.cancel_requested_at,active.cancelStatus||active.cancel_status].join('|');if(!lastState){lastState=sig;return}if(sig===lastState)return;lastState=sig;const mins=active.estimatedMinutes??active.estimated_minutes;const cancel=active.cancelStatus||active.cancel_status;if(cancel==='requested'){try{window.LangarCloud?.showCloudBrowserNotification?.('Langar Bar — Cancellation request sent',`Order ${active.cloudOrderNumber||''}: staff review is pending.`,'langar-cancel-pending')}catch{};return}const title='Langar Bar — Order update';const body=mins?`Order ${active.cloudOrderNumber||''}: about ${mins} minutes. Status: ${active.status}.`:`Order ${active.cloudOrderNumber||''} status: ${active.status}.`;try{window.LangarCloud?.showCloudBrowserNotification?.(title,body,'langar-order-update')}catch{}}
function boot(){let n=0;const t=setInterval(()=>{n++;if(installCloudGuards()||n>40)clearInterval(t)},250);setInterval(()=>{if(!document.hidden)sync()},3500);setTimeout(sync,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.LangarClientV610={sync,refreshCloudMenu,installCloudGuards,version:'6.1.1'};
})();
