const LANGAR_DEFAULT_MENU = [
  { id:'cat-coffee', title:{hr:'Kava',en:'Coffee'}, description:{hr:'Classic espresso, signature coffee and coffee cocktails.',en:'Classic espresso, signature coffee and coffee cocktails.'}, image:'assets/tacos_hero.jpeg', items:[
    ['Ristretto','Kratki intenzivni espresso','Short intense espresso shot','€1.70'],
    ['Espresso','Klasični talijanski espresso','Classic Italian espresso','€1.70'],
    ['Double Espresso','Dvostruki espresso','Double espresso shot','€2.80'],
    ['Decaf Espresso','Espresso bez kofeina','Decaffeinated espresso','€1.70'],
    ['Americano','Vrući ili ledeni espresso s vodom','Hot or iced espresso with water','€2.00'],
    ['Decaf Americano','Vrući ili ledeni americano bez kofeina','Hot or iced decaf americano','€2.00'],
    ['Cappuccino','Espresso s mlijekom i mliječnom pjenom','Espresso with milk and milk foam','€2.50'],
    ['Flat White','Espresso s finom mliječnom kremom','Espresso with silky steamed milk','€2.50'],
    ['Latte','Vrući ili ledeni espresso s mlijekom','Hot or iced espresso with milk','€2.80'],
    ['Flavored Latte','Vrući ili ledeni: vanilija, karamela, lješnjak, pistacija, kokos, cimet i med, jagoda','Hot or iced: vanilla, caramel, hazelnut, pistachio, coconut, cinnamon & honey, strawberry','€3.50'],
    ['Latte Macchiato','Toplo mlijeko s espressom','Steamed milk with espresso','€2.80'],
    ['Mocha','Tamna čokolada ili bijela čokolada s kavom','Dark chocolate or white chocolate with coffee','€3.50'],
    ['Spanish Latte','Vrući ili ledeni latte s kremastom slatkom notom','Hot or iced latte with a creamy sweet note','€3.50'],
    ['Tiramisu Iced Latte','Ledeni latte s okusom tiramisua','Iced latte with tiramisu flavor','€4.50'],
    ['Espresso Tonic','Espresso s tonic vodom','Espresso with tonic water','€2.80'],
    ['Mango Espresso','Espresso s voćnom notom manga','Espresso with mango fruit note','€3.50'],
    ['Mango Iced Latte','Ledeni latte s mangom','Iced latte with mango','€3.50'],
    ['Orange Ocean','Osvježavajuća kombinacija naranče i kave','Refreshing orange and coffee combination','€3.50'],
    ['Langar Mango Velvet','Pire od manga, nota vanilije, mlijeko, espresso','Mango puree, vanilla hint, milk, espresso','€3.50'],
    ['Affogato','Classic, Caramel Lotus ili Pistacija','Classic, Caramel Lotus or Pistachio','€3.80'],
    ['Tiramisu Affogato','Affogato s okusom tiramisua','Affogato with tiramisu flavor','€4.50'],
    ['Classic Espresso Bull','Espresso s energetskim pićem','Espresso with energy drink','€3.80'],
    ['Tropical Espresso Bull','Espresso Bull s tropskim okusom','Espresso Bull with tropical flavor','€4.20'],
    ['Berry Espresso Bull','Espresso Bull s bobičastim voćem','Espresso Bull with berry flavor','€4.20'],
    ['Coconut Espresso Bull','Espresso Bull s okusom kokosa','Espresso Bull with coconut flavor','€4.50'],
    ['Baileys Latte','S Baileysom','With Baileys','€5.20', true],
    ['Kahlua Iced Coffee','S Kahlúom','With Kahlua','€5.20', true],
    ['Irish Coffee','Kava u irskom stilu','Irish-style coffee','€4.50', true],
    ['Amaretto Cappuccino','Cappuccino s amarettom','Cappuccino with amaretto','€4.80', true],
    ['Rum Espresso Tonic','Espresso tonic s rumom','Espresso tonic with rum','€5.00', true],
    ['Mango Coffee Mojito','Koktel kave s mangom i mojito notom','Coffee cocktail with mango and mojito note','€5.20', true],
    ['Espresso Martini','Koktel s espressom','Cocktail with espresso','€4.80', true]
  ]},
  { id:'cat-tea', title:{hr:'Čaj',en:'Tea'}, description:{hr:'Classic, fruit, wellness and iced tea.',en:'Classic, fruit, wellness and iced tea.'}, items:[
    ['Black Tea','Blag i punog okusa','Smooth and full-bodied','€2.00'],['Green Tea','Lagan i osvježavajući','Light and refreshing','€2.00'],['Mint Tea','Svjež i umirujući','Fresh and calming','€2.00'],['Chamomile Tea','Nježan, cvjetni i opuštajući','Soft, floral and relaxing','€2.00'],['Chai Latte','Začinjeni čaj s mlijekom, topao i ugodan','Spiced tea with milk, warm and comforting','€3.00'],['Vanilla Tea Latte','Crni čaj s vanilijom i mlijekom','Black tea with vanilla and milk','€3.00'],['Sour Cherry Tea','Od pravih višanja','Made with real sour cherries','€2.80'],['Mixed Berry Tea','Jagoda, malina i šumsko voće','Strawberry, raspberry and forest fruits','€2.80'],['Citrus Fruit Tea','Naranča, limun i svježa citrusna mješavina','Orange, lemon and fresh citrus blend','€2.80'],['Ginger Lemon Tea','Svježi đumbir i limun, grije i daje energiju','Fresh ginger and lemon, warming and energizing','€2.80'],['Fresh Mint & Lemon','Lagano, osvježavajuće i dobro za probavu','Light, refreshing and digestive','€2.80'],['Honey Cinnamon Tea','Med i cimet u toplom čaju','Honey and cinnamon in warm tea','€3.00'],['Cold Relief Tea','Đumbir, limun, med. Pomaže kod prehlade i jača imunitet','Ginger, lemon, honey. Helps relieve cold and boost immunity','€3.50'],['Relax Tea','Kamilica, menta, med. Umiruje i pomaže kod stresa','Chamomile, mint, honey. Calming and stress-relieving','€3.50'],['Immunity Boost Tea','Zeleni čaj, limun, med, svježi đumbir, cimet','Green tea, lemon, honey, fresh ginger, cinnamon','€3.50'],['Iced Lemon Tea','Ledeni čaj s limunom','Iced tea with lemon','€2.80'],['Iced Peach Tea','Ledeni čaj s breskvom','Iced tea with peach','€2.80'],['Iced Berry Tea','Ledeni čaj s bobičastim voćem','Iced tea with berries','€2.80'],['Iced Green Tea','Opcija u boci / bezalkoholno piće','Bottled / soft drink option','€2.50']
  ]},
  { id:'cat-matcha-smoothies', title:{hr:'Matcha, Smoothieji & Milkshakeovi',en:'Matcha, Smoothies & Milkshakes'}, description:{hr:'Matcha, smoothies and coffee milkshakes.',en:'Matcha, smoothies and coffee milkshakes.'}, items:[
    ['Matcha Latte','Premium matcha s mlijekom. Vrući ili ledeni','Premium matcha with milk. Hot or iced','€4.50'],['Flavored Matcha Latte','Vrući ili ledeni: vanilija, pistacija, kokos, bijela čokolada, jagoda','Hot or iced: vanilla, pistachio, coconut, white chocolate, strawberry','€4.50'],['Matcha Mango Fusion','Premium matcha s mangom','Premium matcha with mango','€4.50'],['Matcha Espresso Fusion','Matcha latte s dozom espressa','Matcha latte with a shot of espresso','€4.50'],['Tropical Smoothie','Tropsko voće u osvježavajućem smoothieju','Tropical fruit in a refreshing smoothie','€4.00'],['Berry Smoothie','Bobičasto voće u smoothieju','Berry fruit smoothie','€4.00'],['Banana Ice Cream Smoothie','Banana i sladoled u kremastom smoothieju','Banana and ice cream in a creamy smoothie','€4.50'],['Berry Chocolate Dream','Bobičasto voće i čokolada','Berries and chocolate','€4.50'],['Banana Nutella Smoothie','Banana i Nutella','Banana and Nutella','€4.50'],['Oreo Ice Smoothie','Oreo smoothie s ledom','Oreo smoothie with ice','€4.50'],['Oreo Coffee Milkshake','Milkshake s kavom i Oreom','Coffee milkshake with Oreo','€4.50'],['Lotus Coffee Milkshake','Milkshake s kavom i Lotus keksom','Coffee milkshake with Lotus biscuit','€4.50'],['Kinder Coffee Milkshake','Milkshake s kavom i Kinder okusom','Coffee milkshake with Kinder flavor','€4.50'],['Peanut Butter Coffee Milkshake','Milkshake s kavom i maslacem od kikirikija','Coffee milkshake with peanut butter','€4.50'],['Kit Kat Coffee Milkshake','Milkshake s kavom i Kit Kat okusom','Coffee milkshake with Kit Kat flavor','€4.50'],['Caramel Almond Coffee Milkshake','Milkshake s kavom, karamelom i bademom','Coffee milkshake with caramel and almond','€4.50'],['Tiramisu Coffee Milkshake','Milkshake s kavom i tiramisu okusom','Coffee milkshake with tiramisu flavor','€4.50']
  ]},
  { id:'cat-protein', title:{hr:'Proteinski napitci',en:'Protein Drinks'}, description:{hr:'Low sugar protein drinks for active lifestyle.',en:'Low sugar protein drinks for active lifestyle.'}, image:'assets/protein_drinks_preview.png', items:[
    ['Protein Espresso Shake','300 ml. Whey protein, mlijeko, espresso. Bez dodanog šećera','300 ml. Whey protein, milk, espresso. No added sugar','€5.90'],['Protein Vanilla Shake','300 ml. Whey protein, mlijeko, aroma vanilije. Bez dodanog šećera','300 ml. Whey protein, milk, vanilla aroma. No added sugar','€5.90'],['Protein Cocoa Shake','300 ml. Whey protein, mlijeko, nezaslađeni kakao. Bez dodanog šećera','300 ml. Whey protein, milk, unsweetened cocoa. No added sugar','€6.20'],['Protein Cinnamon Coffee Shake','300 ml. Whey protein, mlijeko, espresso, cimet. Bez dodanog šećera','300 ml. Whey protein, milk, espresso, cinnamon. No added sugar','€6.20'],['Protein Berry Smoothie','300 ml. Whey protein, mlijeko ili biljno mlijeko, bobičasto voće. Bez dodanog šećera','300 ml. Whey protein, milk or plant-based milk, mixed berries. No added sugar','€6.50'],['Protein Matcha Shake','300 ml. Whey protein, mlijeko, premium matcha. Bez dodanog šećera','300 ml. Whey protein, milk, premium matcha. No added sugar','€6.50']
  ]},
  { id:'cat-soft', title:{hr:'Bezalkoholna pića',en:'Soft Drinks'}, description:{hr:'Soft drinks and water.',en:'Soft drinks and water.'}, items:[
    ['Coca-Cola Can','Limenka Coca-Cole','Coca-Cola can','€3.00'],['Coca-Cola Zero','Coca-Cola bez šećera','Sugar-free Coca-Cola','€3.00'],['Fanta','Gazirano piće od naranče','Orange soft drink','€3.00'],['Fanta Zero','Fanta bez šećera','Sugar-free Fanta','€3.00'],['Orangina Orange','Gazirano piće od naranče','Sparkling orange drink','€2.80'],['Orangina Blood Orange','Gazirano piće od crvene naranče','Sparkling blood orange drink','€2.80'],['Orangina Citrus Mix','Gazirano piće s citrus mixom','Sparkling citrus mix drink','€2.80'],['Cedevita Orange 0.25L','Cedevita naranča','Cedevita orange','€2.00'],['Cedevita Lemon 0.25L','Cedevita limun','Cedevita lemon','€2.00'],['Cedevita Red Orange 0.25L','Cedevita crvena naranča','Cedevita red orange','€2.00'],['Cedevita Multivitamin 0.25L','Cedevita multivitamin','Cedevita multivitamin','€2.00'],['Still Water','Negazirana voda','Still water','€2.00'],['Sparkling Water','Gazirana voda','Sparkling water','€2.00']
  ]},
  { id:'cat-beer-wine', title:{hr:'Pivo & vino',en:'Beer & Wine'}, description:{hr:'Alcoholic drinks are served only to persons 18+.',en:'Alcoholic drinks are served only to persons 18+.'}, items:[
    ['Karlovačko 0.5L','Alkoholno pivo','Alcoholic beer','€3.00', true],['Heineken 0.33L','Alkoholno pivo','Alcoholic beer','€3.00', true],['Desperados','Alkoholno pivo','Alcoholic beer','€3.00', true],['Heineken 0.0','Bezalkoholno pivo','Non-alcoholic beer','€3.00'],['Radler 0.0','Bezalkoholni radler','Non-alcoholic radler','€3.00'],['Krauthaker Graševina','Bijelo vino. Svježe, elegantno i uravnoteženo hrvatsko vino iz vinarije Krauthaker, Kutjevo','White wine. Fresh, elegant and balanced Croatian wine from Krauthaker Winery, Kutjevo','1 dcl €2.80 | Bottle €21.00', true],['Krauthaker Sauvignon Vidim','Bijelo vino. Aromatično, svježe i voćno','White wine. Aromatic, fresh and fruity','1 dcl €3.20 | Bottle €24.00', true],['Krauthaker Pinot Crni','Crno vino. Nježno i elegantno s finim voćnim notama','Red wine. Smooth and elegant with fine fruit notes','1 dcl €3.60 | Bottle €27.00', true],['Krauthaker Merlot','Crno vino. Mekano, zaokruženo i puno','Red wine. Soft, rounded and full-bodied','1 dcl €3.50 | Bottle €26.00', true],['Gemišt 2 dcl','1 dcl Krauthaker Graševina + 1 dcl mineralna voda','1 dcl Krauthaker Graševina + 1 dcl sparkling water','€3.80', true]
  ]},
  { id:'cat-combo', title:{hr:'Combo ponuda',en:'Combo Menu'}, description:{hr:'Coffee, croissant, muffin and wine pairing combos.',en:'Coffee, croissant, muffin and wine pairing combos.'}, items:[
    ['Wine Pairing Plate for One','Jedna vrsta sira, kulen kobasica, pršut, sezonsko voće i hrskavi zalogaji','One cheese selection, kulen sausage, prosciutto, seasonal fruit and crispy bites','€8.50'],['1 dcl Wine + Wine Pairing Plate for One','Odabir vina 1 dcl: Graševina, Sauvignon Vidim, Pinot Crni ili Merlot','Choose one wine by 1 dcl: Graševina, Sauvignon Vidim, Pinot Crni or Merlot','€11.50', true],['Bottle of White Wine + Wine Pairing Plate for 2','Dostupno uz Krauthaker Graševinu ili Krauthaker Sauvignon Vidim','Available with Krauthaker Graševina or Krauthaker Sauvignon Vidim','€34.00', true],['Bottle of Red Wine + Wine Pairing Plate for 2','Dostupno uz Krauthaker Pinot Crni ili Krauthaker Merlot','Available with Krauthaker Pinot Crni or Krauthaker Merlot','€39.00', true],['Espresso + Croissant','Espresso i kroasan','Espresso and croissant','€4.00'],['Cappuccino + Croissant','Cappuccino i kroasan','Cappuccino and croissant','€5.00'],['Latte + Croissant','Latte i kroasan','Latte and croissant','€5.00'],['Pistachio Latte + Croissant','Premium combo: pistachio latte i kroasan','Premium combo: pistachio latte and croissant','€5.60'],['Spanish Latte + Muffin','Premium combo: Spanish latte i muffin','Premium combo: Spanish latte and muffin','€5.60']
  ]},
  { id:'cat-dessert', title:{hr:'Deserti & sladoled',en:'Desserts & Ice Cream'}, description:{hr:'Desserts, pastries and soft-serve ice cream.',en:'Desserts, pastries and soft-serve ice cream.'}, items:[
    ['Cupcake with Ice Cream','Poslužuje se s čokoladnim umakom, umakom od pistacije ili karamel umakom','Served with chocolate sauce, pistachio sauce or caramel sauce','€4.50'],['Langar Warm Mug Cake','Topli kolač poslužen u šalici. Čokoladni umak, umak od pistacije ili karamel umak','Warm cake served in a mug. Chocolate sauce, pistachio sauce or caramel sauce','€4.50'],['Tiramisu Cup','Tiramisu desert u čaši','Tiramisu dessert cup','€4.00'],['Napoleon','Kremasti lisnati kolač','Creamy layered pastry dessert','€3.80'],['Apple Pie','Pita od jabuka','Apple pie','€3.00'],['Chocolate Croissant','Kroasan s čokoladom','Chocolate croissant','€3.00'],['Pistachio Croissant','Kroasan s pistacijom','Pistachio croissant','€3.00'],['Turkish Baklava','Po komadu','Per piece','€1.80 each'],['Coconut Cookie','Po komadu','Per piece','€1.50 each'],['Pistachio Ice Cream','Sladoled iz aparata, nije na kuglice','Soft-serve ice cream, not scooped','€3.00'],['Nutella Ice Cream','Sladoled iz aparata, nije na kuglice','Soft-serve ice cream, not scooped','€3.00'],['Caramel Ice Cream','Sladoled iz aparata, nije na kuglice','Soft-serve ice cream, not scooped','€3.00'],['Mango Ice Cream','Sladoled iz aparata, nije na kuglice','Soft-serve ice cream, not scooped','€3.00']
  ]},
  { id:'cat-toast', title:{hr:'Tost sendviči',en:'Toast Sandwiches'}, description:{hr:'Brzi, topli i ukusni sendviči.',en:'Quick, warm and tasty sandwiches.'}, image:'assets/focaccia_sandwich_preview.png', items:[
    ['Chicken Pesto & Cheese','Piletina, pesto umak, sir','Chicken, pesto sauce, cheese','€3.90'],
    ['Tuna Sandwich','Tuna, umak, svježi dodaci','Tuna, sauce, fresh additions','€3.80'],
    ['Margherita','Umak od rajčice, mozzarella, začini','Tomato sauce, mozzarella, herbs','€3.80'],
    ['Cheesy Mortadella','Mortadela, sir, umak','Mortadella, cheese, sauce','€3.80'],
    ['Avocado Chicken','Piletina, avokado, sir, umak','Chicken, avocado, cheese, sauce','€3.80']
  ]},
  { id:'cat-tacos', title:{hr:'Taco Menu',en:'Taco Menu'}, description:{hr:'Signature tacosi s bogatim punjenjima i umacima.',en:'Signature tacos with loaded fillings and sauces.'}, image:'assets/tacos_hero.jpeg', items:[
    ['Golden Chicken Taco','Hrskava pržena piletina, coleslaw salata, rikola, teriyaki umak, sezam','Crunchy fried chicken, coleslaw salad, arugula, teriyaki sauce, sesame','€6.80'],
    ['Crunchy Prawn Taco','Hrskave pržene kozice, coleslaw salata, rikola, teriyaki umak, sezam','Crunchy fried prawns, coleslaw salad, arugula, teriyaki sauce, sesame','€6.80'],
    ['Tuna Taco','Tuna, pico de gallo, kukuruz, kiseli krastavci, rikola, lime mayo umak, hrskavi luk','Tuna, pico de gallo, sweet corn, pickles, arugula, lime mayo, crispy onion','€6.80'],
    ['Chicken Curry Taco','Pileći zabatak bez kosti, basmati riža, curry umak','Boneless chicken thigh, basmati rice, curry sauce','€6.80'],
    ['Picante Chicken Taco','Trgana piletina, mozzarella sir, mayo-sriracha umak','Shredded chicken, mozzarella cheese, mayo-sriracha sauce','€6.80']
  ]},
  { id:'cat-focaccia-pizza', title:{hr:'Focaccia Pizza',en:'Focaccia Pizza'}, description:{hr:'Male pravokutne pizze na focaccia bazi.',en:'Small rectangular pizzas on a focaccia base.'}, image:'assets/quesadilla_real.jpeg', items:[
    ['Bacon Pizza','Umak od rajčice, slanina, mozzarella','Tomato sauce, bacon, mozzarella','€7.80'],
    ['Prosciutto Pizza','Umak od rajčice, mozzarella, pršut, burrata, rikola, pesto umak','Tomato sauce, mozzarella, prosciutto, burrata, arugula, pesto sauce','€8.90'],
    ['Mortadella Truffle Pizza','Umak od rajčice, mortadela s tartufom, mozzarella, burrata, zeleni umak','Tomato sauce, truffle mortadella, mozzarella, burrata, green sauce','€8.30'],
    ['Margherita Pizza','Umak od rajčice, mozzarella, maslinovo ulje','Tomato sauce, mozzarella, olive oil','€7.00']
  ]},
  { id:'cat-tapas', title:{hr:'Tapas',en:'Tapas'}, description:{hr:'Mali zalogaji za dijeljenje i druženje.',en:'Small bites for sharing and social moments.'}, image:'assets/prawn_tacos.jpeg', items:[
    ['Hummus Tapas','Humus s dodacima','Hummus with additions','€5.80'],
    ['Eggplant Hummus Tapas','Humus s patlidžanom','Hummus with eggplant','€5.80'],
    ['Tuna Tapas','Tuna tapas s dodacima','Tuna tapas with additions','€5.80'],
    ['Chicken Avocado Tapas','Piletina, avokado i dodaci','Chicken, avocado and additions','€5.80']
  ]}

].map(cat => ({...cat, items: cat.items.map((it,idx)=>({id: `${cat.id}-${idx+1}`, name: it[0], desc:{hr:it[1], en:it[2]}, price: it[3], isAlcoholic: !!it[4], available:true, orderable: !it[4], rewardEligible: !it[4]}))}));
