(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); let C=null, selected=[];
async function client(){for(let i=0;i<80;i++){C=window.LangarAdminCloud?.client||window.LangarCloud?.client;if(C)return C;await sleep(125)}return null}
function toast(m,ok=true){let n=$('#v558toast');if(!n){n=document.createElement('div');n.id='v558toast';document.body.appendChild(n)}n.className='v558-toast '+(ok?'ok':'bad');n.textContent=m;clearTimeout(n.t);n.t=setTimeout(()=>n.remove(),4500)}
function l(){return window.state?.lang==='hr'?'hr':'en'}
function times(){return ['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00']}
async function availability(form){const c=C||await client();if(!c)return;const date=form.date.value,time=form.time.value,area=form.area.value,guests=+form.guests.value||0,box=$('#v558Tables');if(!date||!time||!guests){box.innerHTML='<p>Select date, time and number of guests.</p>';return}box.innerHTML='<p>Checking available tables…</p>';const {data,error}=await c.rpc('customer_table_availability_v558',{p_date:date,p_time:time,p_area:area,p_guests:guests});if(error){box.innerHTML='<p class="error">'+esc(error.message)+'</p>';return}selected=[];const need=Math.ceil(guests/4);box.innerHTML=`<p class="v558-hint">${l()==='hr'?`Odaberite ${need} stol(a). Svaki stol prima do 4 osobe.`:`Choose ${need} table(s). Each table seats up to 4 guests.`}</p><div class="v558-table-grid">${(data||[]).map(t=>`<button type="button" class="v558-table ${t.available?'available':'booked'}" data-id="${t.id}" ${t.available?'':'disabled'}><b>${esc(t.label)}</b><small>${t.area==='inside'?'Inside':'Terrace'} · 4 seats</small><span>${t.available?'Available':'Booked'}</span></button>`).join('')}</div>`;
$$('.v558-table.available',box).forEach(b=>b.onclick=()=>{const id=b.dataset.id;if(selected.includes(id)){selected=selected.filter(x=>x!==id);b.classList.remove('selected')}else if(selected.length<need){selected.push(id);b.classList.add('selected')}else toast(`Select exactly ${need} table(s).`,false)});
}
function buildCustomer(){const old=$('#reservationForm');if(!old||old.dataset.v558)return;const form=old.cloneNode(false);form.id='reservationForm';form.dataset.v558='1';form.className=old.className;form.innerHTML=`<div class="reservation-board v558-board"><label><span>Date</span><input type="date" name="date" required></label><label><span>Time</span><select name="time" required><option value="">Choose time</option>${times().map(t=>`<option>${t}</option>`).join('')}</select></label><label><span>Area</span><select name="area"><option value="any">No preference</option><option value="inside">Inside</option><option value="terrace">Terrace</option></select></label><label><span>Name and surname</span><input name="name" minlength="2" required></label><label><span>Phone number</span><input name="phone" type="tel" minlength="7" required></label><label><span>Guests</span><input name="guests" type="number" min="1" max="40" required></label><label class="full"><span>Note (optional)</span><textarea name="note" placeholder="Birthday, child seat, accessibility, special request…"></textarea></label><section id="v558Tables" class="v558-availability"><p>Select date, time and number of guests to see free tables.</p></section><button class="primary full" type="submit">Confirm reservation instantly</button><p class="legal mini">Available tables are confirmed immediately. No admin approval is required.</p></div>`;old.replaceWith(form);
const min=new Date();min.setMinutes(min.getMinutes()-min.getTimezoneOffset());form.date.min=min.toISOString().slice(0,10);form.date.value=form.date.min;
['date','time','area','guests'].forEach(n=>form[n].addEventListener('change',()=>availability(form)));
form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const c=C||await client();if(!c)return;const need=Math.ceil((+form.guests.value||1)/4);if(selected.length!==need)return toast(`Please select ${need} available table(s).`,false);const btn=form.querySelector('button[type=submit]');btn.disabled=true;const {data,error}=await c.rpc('customer_create_reservation_v558',{p_date:form.date.value,p_time:form.time.value,p_name:form.name.value.trim(),p_phone:form.phone.value.trim(),p_guests:+form.guests.value,p_area:form.area.value,p_note:form.note.value.trim(),p_table_ids:selected});btn.disabled=false;if(error)return toast(error.message,false);toast(data.message||'Reservation confirmed.');selected=[];await renderMine();availability(form)} ,true);
renderMine();}
async function renderMine(){const box=$('#myReservations');if(!box)return;const c=C||await client();const {data:{session}}=await c.auth.getSession();if(!session)return;const {data}=await c.from('reservations').select('id,reservation_date,reservation_time,guests,area,status,note,admin_note,reservation_table_assignments(table_id,restaurant_tables(label))').eq('user_id',session.user.id).order('reservation_date',{ascending:false}).order('reservation_time',{ascending:false});box.innerHTML=(data||[]).map(r=>{const tables=(r.reservation_table_assignments||[]).map(x=>x.restaurant_tables?.label).filter(Boolean).join(', ');return `<article class="v558-my-res"><div><b>${esc(r.reservation_date)} · ${esc(String(r.reservation_time).slice(0,5))}</b><span>${esc(r.status)}</span></div><p><b>${esc(tables||'Table assigned')}</b> · ${r.guests} guests · ${esc(r.area||'')}</p>${r.note?`<small>${esc(r.note)}</small>`:''}</article>`}).join('')||'<p>No reservations yet.</p>'}
async function adminAction(id,status){const note=prompt('Optional message to customer:','');if(note===null)return;const c=C||await client();let {data,error}=await c.rpc('admin_update_reservation_v558',{p_id:id,p_status:status,p_note:note});if(error){({data,error}=await c.rpc('admin_update_reservation_v520',{p_id:id,p_status:status,p_note:note}))}if(error)return toast(error.message,false);toast(data?.message||'Updated');renderAdmin()}
async function renderAdmin(){const box=$('#reservationsAdmin');if(!box)return;const c=C||await client();const {data,error}=await c.from('reservations').select('*,reservation_table_assignments(table_id,restaurant_tables(label))').order('reservation_date').order('reservation_time');if(error)return;box.innerHTML=(data||[]).map(r=>{const tables=(r.reservation_table_assignments||[]).map(x=>x.restaurant_tables?.label).filter(Boolean).join(', ')||r.table_label||'—';return `<article class="v558-admin-res"><div><h3>${esc(r.reservation_date)} · ${esc(String(r.reservation_time).slice(0,5))}</h3><p><b>${esc(r.customer_name)}</b> · ${esc(r.phone)} · ${r.guests} guests</p><p><b>Tables:</b> ${esc(tables)} · ${esc(r.area||'')}</p>${r.note?`<p><b>Note:</b> ${esc(r.note)}</p>`:''}<small>Status: <b>${esc(r.status)}</b>${r.auto_confirmed?' · Automatically confirmed':''}</small></div><div class="v558-actions"><button class="message" data-a="message" data-id="${r.id}">Message</button><button class="complete" data-a="completed" data-id="${r.id}">Completed</button><button class="noshow" data-a="no_show" data-id="${r.id}">No-show</button><button class="cancel" data-a="cancelled" data-id="${r.id}">Cancel</button></div></article>`}).join('')||'<p>No reservations.</p>';$$('[data-a]',box).forEach(b=>b.onclick=()=>adminAction(b.dataset.id,b.dataset.a==='message'?data.find(x=>x.id===b.dataset.id)?.status||'confirmed':b.dataset.a))}
function hook(){const old=window.showPanel;window.showPanel=function(id){const x=old?.apply(this,arguments);if(id==='reservationsPanel')setTimeout(renderAdmin,100);return x}}
async function init(){await client();buildCustomer();hook();renderAdmin();C?.channel('v558-res').on('postgres_changes',{event:'*',schema:'public',table:'reservations'},()=>{renderMine();if(!$('#reservationsPanel')?.classList.contains('hidden'))renderAdmin()}).subscribe();setInterval(()=>{if(!$('#reservationForm')?.dataset.v558)buildCustomer()},1500)}
window.addEventListener('load',()=>setTimeout(init,1200));
})();
