begin;
create extension if not exists pgcrypto;
create table if not exists public.restaurant_tables(id uuid primary key default gen_random_uuid(),label text unique not null,area text not null check(area in('inside','terrace')),capacity int not null default 4,active boolean not null default true,sort_order int not null default 10,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.restaurant_tables add column if not exists updated_at timestamptz not null default now();
insert into public.restaurant_tables(label,area,capacity,active,sort_order) select 'Inside T'||n,'inside',4,true,n*10 from generate_series(1,5)n on conflict(label) do update set area='inside',capacity=4,active=true,sort_order=excluded.sort_order,updated_at=now();
insert into public.restaurant_tables(label,area,capacity,active,sort_order) select 'Terrace T'||n,'terrace',4,true,100+n*10 from generate_series(1,15)n on conflict(label) do update set area='terrace',capacity=4,active=true,sort_order=excluded.sort_order,updated_at=now();
create table if not exists public.reservation_table_assignments(reservation_id uuid not null references public.reservations(id) on delete cascade,table_id uuid not null references public.restaurant_tables(id) on delete restrict,primary key(reservation_id,table_id));
create index if not exists reservation_assignments_table_idx on public.reservation_table_assignments(table_id,reservation_id);
alter table public.reservations add column if not exists updated_at timestamptz not null default now();
alter table public.reservations add column if not exists duration_minutes int not null default 90;
alter table public.reservations add column if not exists auto_confirmed boolean not null default false;
alter table public.reservations add column if not exists admin_note text;
create or replace function public.customer_table_availability_v558(p_date date,p_time time,p_area text default 'any',p_guests int default 1)
returns table(id uuid,label text,area text,capacity int,available boolean) language sql security definer set search_path=public as $$
select t.id,t.label,t.area,t.capacity,not exists(select 1 from reservation_table_assignments a join reservations r on r.id=a.reservation_id where a.table_id=t.id and r.status in('pending','confirmed') and tsrange(r.reservation_date+r.reservation_time,r.reservation_date+r.reservation_time+make_interval(mins=>coalesce(r.duration_minutes,90)),'[)') && tsrange(p_date+p_time,p_date+p_time+interval '90 minutes','[)')) from restaurant_tables t where t.active and (p_area='any' or t.area=p_area) order by t.area,t.sort_order$$;
grant execute on function public.customer_table_availability_v558(date,time,text,int) to anon,authenticated;
create or replace function public.customer_create_reservation_v558(p_date date,p_time time,p_name text,p_phone text,p_guests int,p_area text,p_note text,p_table_ids uuid[])
returns jsonb language plpgsql security definer set search_path=public as $$
declare rid uuid;need int;cnt int;labels text;chosen_area text;
begin
 if auth.uid() is null then raise exception 'Login required';end if;if length(trim(p_name))<2 then raise exception 'Full name is required';end if;if length(regexp_replace(p_phone,'\D','','g'))<7 then raise exception 'Valid phone number is required';end if;if p_guests<1 or p_guests>40 then raise exception 'Invalid guest count';end if;if p_date<current_date then raise exception 'Date is in the past';end if;
 need:=ceil(p_guests/4.0);if coalesce(array_length(p_table_ids,1),0)<>need then raise exception 'Please select exactly % table(s)',need;end if;
 perform 1 from restaurant_tables where id=any(p_table_ids) and active for update;
 select count(*),string_agg(label,', ' order by sort_order),min(area) into cnt,labels,chosen_area from restaurant_tables where id=any(p_table_ids) and active and (p_area='any' or area=p_area);
 if cnt<>need then raise exception 'One or more selected tables are invalid';end if;
 if exists(select 1 from reservation_table_assignments a join reservations r on r.id=a.reservation_id where a.table_id=any(p_table_ids) and r.status in('pending','confirmed') and tsrange(r.reservation_date+r.reservation_time,r.reservation_date+r.reservation_time+make_interval(mins=>coalesce(r.duration_minutes,90)),'[)') && tsrange(p_date+p_time,p_date+p_time+interval '90 minutes','[)')) then raise exception 'One of the selected tables has just been booked. Please choose again';end if;
 insert into reservations(user_id,customer_name,phone,reservation_date,reservation_time,guests,area,note,status,duration_minutes,auto_confirmed,table_label,updated_at) values(auth.uid(),trim(p_name),trim(p_phone),p_date,p_time,p_guests,case when p_area='any' then chosen_area else p_area end,nullif(trim(p_note),''),'confirmed',90,true,labels,now()) returning id into rid;
 insert into reservation_table_assignments(reservation_id,table_id) select rid,unnest(p_table_ids);
 insert into inbox_messages(user_id,type,title_en,body_en,title_hr,body_hr,data,created_at,is_read,is_deleted) values(auth.uid(),'reservation','Reservation confirmed',format('Your reservation is confirmed for %s at %s. Table(s): %s.',p_date,to_char(p_time,'HH24:MI'),labels),'Rezervacija potvrđena',format('Vaša rezervacija je potvrđena za %s u %s. Stol(ovi): %s.',p_date,to_char(p_time,'HH24:MI'),labels),jsonb_build_object('reservation_id',rid,'tables',labels),now(),false,false);
 return jsonb_build_object('ok',true,'status','confirmed','reservation_id',rid,'tables',labels,'message',format('Reservation confirmed. Table(s): %s',labels));
end$$;
grant execute on function public.customer_create_reservation_v558(date,time,text,text,int,text,text,uuid[]) to authenticated;
create or replace function public.admin_update_reservation_v558(p_id uuid,p_status text,p_note text default '') returns jsonb language plpgsql security definer set search_path=public as $$declare r reservations;begin if not exists(select 1 from admin_members where user_id=auth.uid() and active) then raise exception 'Admin required';end if;if p_status not in('confirmed','cancelled','completed','no_show','rejected') then raise exception 'Invalid status';end if;update reservations set status=p_status,admin_note=nullif(trim(p_note),''),updated_at=now() where id=p_id returning * into r;if r.id is null then raise exception 'Reservation not found';end if;insert into inbox_messages(user_id,type,title_en,body_en,title_hr,body_hr,data,created_at,is_read,is_deleted) values(r.user_id,'reservation','Reservation update',format('Your reservation for %s at %s is now %s. %s',r.reservation_date,to_char(r.reservation_time,'HH24:MI'),p_status,coalesce(p_note,'')),'Ažuriranje rezervacije',format('Vaša rezervacija za %s u %s sada je %s. %s',r.reservation_date,to_char(r.reservation_time,'HH24:MI'),p_status,coalesce(p_note,'')),jsonb_build_object('reservation_id',r.id,'status',p_status),now(),false,false);return jsonb_build_object('ok',true,'message','Reservation updated and customer notified');end$$;
grant execute on function public.admin_update_reservation_v558(uuid,text,text) to authenticated;
create or replace function public.admin_update_reservation_v520(p_id uuid,p_note text,p_status text) returns jsonb language sql security definer set search_path=public as $$select public.admin_update_reservation_v558($1,$3,$2)$$;
grant execute on function public.admin_update_reservation_v520(uuid,text,text) to authenticated;
commit;
select count(*) filter(where area='inside' and active) inside_tables,count(*) filter(where area='terrace' and active) terrace_tables,to_regprocedure('public.customer_create_reservation_v558(date,time without time zone,text,text,integer,text,text,uuid[])') is not null as ready from restaurant_tables;
