-- Langar Bar V5.4.0 Smart Drink Knowledge Base
create extension if not exists pg_trgm;
create table if not exists public.langar_knowledge_entries (id uuid primary key default gen_random_uuid(),slug text unique not null,category text not null,name_en text not null,name_hr text not null,summary_en text not null,summary_hr text not null,details_en text,details_hr text,recipe jsonb not null default '{}'::jsonb,keywords text[] not null default '{}',aliases text[] not null default '{}',allergen_note text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.barista_questions add column if not exists answer_source text default 'human';
alter table public.barista_questions add column if not exists matched_knowledge_id uuid references public.langar_knowledge_entries(id);
alter table public.barista_questions add column if not exists answered_at timestamptz;
create index if not exists langar_knowledge_name_en_trgm on public.langar_knowledge_entries using gin (name_en gin_trgm_ops);
create index if not exists langar_knowledge_name_hr_trgm on public.langar_knowledge_entries using gin (name_hr gin_trgm_ops);
insert into public.langar_knowledge_entries(slug,category,name_en,name_hr,summary_en,summary_hr,details_en,details_hr,recipe,keywords,aliases,allergen_note,active) values
('espresso','espresso','Espresso','Espresso','Concentrated coffee extracted under pressure.','Koncentrirana kava ekstrahirana pod pritiskom.','Concentrated coffee extracted under pressure. Typical values vary by café size and recipe.','Koncentrirana kava ekstrahirana pod pritiskom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":0,"foam_ml":0,"cup_ml":40,"caffeine_mg_min":55,"caffeine_mg_max":75,"calories_min":2,"calories_max":5}'::jsonb,ARRAY['espresso','shot','short coffee','crema']::text[],ARRAY['espresso','shot','short coffee','crema']::text[],NULL,true),
('doppio','espresso','Doppio','Doppio','A double espresso with roughly twice the coffee and beverage yield.','Dvostruki espresso s približno dvostrukom dozom i količinom napitka.','A double espresso with roughly twice the coffee and beverage yield. Typical values vary by café size and recipe.','Dvostruki espresso s približno dvostrukom dozom i količinom napitka. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":36,"espresso_ml":72,"water_ml":0,"milk_ml":0,"foam_ml":0,"cup_ml":80,"caffeine_mg_min":110,"caffeine_mg_max":150,"calories_min":4,"calories_max":10}'::jsonb,ARRAY['double espresso','doppio','two shots']::text[],ARRAY['double espresso','doppio','two shots']::text[],NULL,true),
('ristretto','espresso','Ristretto','Ristretto','A shorter, more concentrated espresso extraction.','Kraća i koncentriranija espresso ekstrakcija.','A shorter, more concentrated espresso extraction. Typical values vary by café size and recipe.','Kraća i koncentriranija espresso ekstrakcija. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":20,"water_ml":0,"milk_ml":0,"foam_ml":0,"cup_ml":25,"caffeine_mg_min":45,"caffeine_mg_max":70,"calories_min":2,"calories_max":5}'::jsonb,ARRAY['ristretto','short espresso','concentrated']::text[],ARRAY['ristretto','short espresso','concentrated']::text[],NULL,true),
('lungo','espresso','Lungo','Lungo','A longer espresso extraction with more water passing through the coffee.','Dulja espresso ekstrakcija s više vode kroz kavu.','A longer espresso extraction with more water passing through the coffee. Typical values vary by café size and recipe.','Dulja espresso ekstrakcija s više vode kroz kavu. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":60,"water_ml":0,"milk_ml":0,"foam_ml":0,"cup_ml":70,"caffeine_mg_min":60,"caffeine_mg_max":90,"calories_min":3,"calories_max":7}'::jsonb,ARRAY['lungo','long espresso']::text[],ARRAY['lungo','long espresso']::text[],NULL,true),
('americano','espresso','Americano','Americano','Espresso diluted with hot water; no milk in the standard recipe.','Espresso razrijeđen vrućom vodom; standardno bez mlijeka.','Espresso diluted with hot water; no milk in the standard recipe. Typical values vary by café size and recipe.','Espresso razrijeđen vrućom vodom; standardno bez mlijeka. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":120,"milk_ml":0,"foam_ml":0,"cup_ml":180,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":2,"calories_max":7}'::jsonb,ARRAY['americano','espresso water','black coffee']::text[],ARRAY['americano','espresso water','black coffee']::text[],NULL,true),
('long-black','espresso','Long Black','Long Black','Hot water topped with espresso, often preserving more crema than an Americano.','Vruća voda prelivena espressom, često s više sačuvane creme nego Americano.','Hot water topped with espresso, often preserving more crema than an Americano. Typical values vary by café size and recipe.','Vruća voda prelivena espressom, često s više sačuvane creme nego Americano. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":100,"milk_ml":0,"foam_ml":0,"cup_ml":150,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":2,"calories_max":7}'::jsonb,ARRAY['long black','black coffee','water espresso']::text[],ARRAY['long black','black coffee','water espresso']::text[],NULL,true),
('cappuccino','milk-coffee','Cappuccino','Cappuccino','Espresso with steamed milk and a clearly defined layer of milk foam.','Espresso s toplim mlijekom i jasno izraženim slojem mliječne pjene.','Espresso with steamed milk and a clearly defined layer of milk foam. Typical values vary by café size and recipe.','Espresso s toplim mlijekom i jasno izraženim slojem mliječne pjene. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":60,"milk_ml":60,"foam_ml":50,"cup_ml":180,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":70,"calories_max":130}'::jsonb,ARRAY['cappuccino','foam','milk coffee','kapučino']::text[],ARRAY['cappuccino','foam','milk coffee','kapučino']::text[],'Contains milk unless ordered without dairy.',true),
('latte','milk-coffee','Caffè Latte','Caffè Latte','Espresso with more steamed milk and only a thin layer of microfoam.','Espresso s više toplog mlijeka i tankim slojem mikropjene.','Espresso with more steamed milk and only a thin layer of microfoam. Typical values vary by café size and recipe.','Espresso s više toplog mlijeka i tankim slojem mikropjene. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":180,"foam_ml":15,"cup_ml":250,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":110,"calories_max":190}'::jsonb,ARRAY['latte','cafe latte','milk coffee','large milk coffee']::text[],ARRAY['latte','cafe latte','milk coffee','large milk coffee']::text[],'Contains milk unless ordered without dairy.',true),
('flat-white','milk-coffee','Flat White','Flat White','Usually a double espresso with silky microfoam and less milk than a latte.','Obično dvostruki espresso sa svilenkastom mikropjenom i manje mlijeka nego latte.','Usually a double espresso with silky microfoam and less milk than a latte. Typical values vary by café size and recipe.','Obično dvostruki espresso sa svilenkastom mikropjenom i manje mlijeka nego latte. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":140,"foam_ml":10,"cup_ml":190,"caffeine_mg_min":80,"caffeine_mg_max":130,"calories_min":85,"calories_max":150}'::jsonb,ARRAY['flat white','microfoam','strong latte']::text[],ARRAY['flat white','microfoam','strong latte']::text[],'Contains milk unless ordered without dairy.',true),
('macchiato','milk-coffee','Espresso Macchiato','Espresso Macchiato','Espresso marked with a small spoon of milk foam.','Espresso označen malom količinom mliječne pjene.','Espresso marked with a small spoon of milk foam. Typical values vary by café size and recipe.','Espresso označen malom količinom mliječne pjene. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":5,"foam_ml":10,"cup_ml":60,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":8,"calories_max":25}'::jsonb,ARRAY['macchiato','espresso macchiato','small milk']::text[],ARRAY['macchiato','espresso macchiato','small milk']::text[],'Contains milk unless ordered without dairy.',true),
('cortado','milk-coffee','Cortado','Cortado','Espresso balanced with a similar amount of warm milk and very little foam.','Espresso uravnotežen s približno jednakom količinom toplog mlijeka i malo pjene.','Espresso balanced with a similar amount of warm milk and very little foam. Typical values vary by café size and recipe.','Espresso uravnotežen s približno jednakom količinom toplog mlijeka i malo pjene. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":45,"foam_ml":5,"cup_ml":90,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":30,"calories_max":65}'::jsonb,ARRAY['cortado','equal milk espresso']::text[],ARRAY['cortado','equal milk espresso']::text[],'Contains milk unless ordered without dairy.',true),
('piccolo','milk-coffee','Piccolo Latte','Piccolo Latte','A small milk coffee based on ristretto or espresso with silky milk.','Mala mliječna kava na bazi ristretta ili espressa sa svilenkastim mlijekom.','A small milk coffee based on ristretto or espresso with silky milk. Typical values vary by café size and recipe.','Mala mliječna kava na bazi ristretta ili espressa sa svilenkastim mlijekom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":25,"water_ml":0,"milk_ml":70,"foam_ml":5,"cup_ml":100,"caffeine_mg_min":45,"caffeine_mg_max":70,"calories_min":45,"calories_max":80}'::jsonb,ARRAY['piccolo','small latte']::text[],ARRAY['piccolo','small latte']::text[],'Contains milk unless ordered without dairy.',true),
('mocha','milk-coffee','Caffè Mocha','Caffè Mocha','Espresso, chocolate and steamed milk, usually with light foam.','Espresso, čokolada i toplo mlijeko, obično s laganom pjenom.','Espresso, chocolate and steamed milk, usually with light foam. Typical values vary by café size and recipe.','Espresso, čokolada i toplo mlijeko, obično s laganom pjenom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":160,"foam_ml":15,"cup_ml":250,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":190,"calories_max":330}'::jsonb,ARRAY['mocha','chocolate coffee','cafe mocha']::text[],ARRAY['mocha','chocolate coffee','cafe mocha']::text[],'Contains milk unless ordered without dairy.',true),
('affogato','dessert','Affogato','Affogato','A shot of espresso poured over vanilla ice cream.','Espresso preliven preko sladoleda od vanilije.','A shot of espresso poured over vanilla ice cream. Typical values vary by café size and recipe.','Espresso preliven preko sladoleda od vanilije. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":0,"foam_ml":0,"cup_ml":140,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":140,"calories_max":260}'::jsonb,ARRAY['affogato','ice cream espresso','dessert coffee']::text[],ARRAY['affogato','ice cream espresso','dessert coffee']::text[],NULL,true),
('iced-latte','cold-coffee','Iced Latte','Iced Latte','Espresso, cold milk and ice; typically no foam.','Espresso, hladno mlijeko i led; obično bez pjene.','Espresso, cold milk and ice; typically no foam. Typical values vary by café size and recipe.','Espresso, hladno mlijeko i led; obično bez pjene. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":0,"milk_ml":180,"foam_ml":0,"cup_ml":350,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":100,"calories_max":190}'::jsonb,ARRAY['iced latte','cold latte','ice milk coffee']::text[],ARRAY['iced latte','cold latte','ice milk coffee']::text[],'Contains milk unless ordered without dairy.',true),
('iced-americano','cold-coffee','Iced Americano','Iced Americano','Espresso, cold water and ice; no milk by default.','Espresso, hladna voda i led; standardno bez mlijeka.','Espresso, cold water and ice; no milk by default. Typical values vary by café size and recipe.','Espresso, hladna voda i led; standardno bez mlijeka. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":160,"milk_ml":0,"foam_ml":0,"cup_ml":350,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":2,"calories_max":7}'::jsonb,ARRAY['iced americano','cold black coffee']::text[],ARRAY['iced americano','cold black coffee']::text[],NULL,true),
('cold-brew','cold-coffee','Cold Brew','Cold Brew','Coarsely ground coffee steeped in cold water for many hours and filtered.','Grubo mljevena kava namakana satima u hladnoj vodi i zatim filtrirana.','Coarsely ground coffee steeped in cold water for many hours and filtered. Typical values vary by café size and recipe.','Grubo mljevena kava namakana satima u hladnoj vodi i zatim filtrirana. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":70,"espresso_ml":0,"water_ml":500,"milk_ml":0,"foam_ml":0,"cup_ml":300,"caffeine_mg_min":120,"caffeine_mg_max":220,"calories_min":2,"calories_max":10}'::jsonb,ARRAY['cold brew','cold extraction','steeped coffee']::text[],ARRAY['cold brew','cold extraction','steeped coffee']::text[],NULL,true),
('espresso-tonic','cold-coffee','Espresso Tonic','Espresso Tonic','Espresso served over tonic water and ice, bright and bittersweet.','Espresso poslužen preko tonika i leda, svjež i gorko-sladak.','Espresso served over tonic water and ice, bright and bittersweet. Typical values vary by café size and recipe.','Espresso poslužen preko tonika i leda, svjež i gorko-sladak. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":36,"water_ml":150,"milk_ml":0,"foam_ml":0,"cup_ml":300,"caffeine_mg_min":55,"caffeine_mg_max":80,"calories_min":45,"calories_max":110}'::jsonb,ARRAY['espresso tonic','tonic coffee']::text[],ARRAY['espresso tonic','tonic coffee']::text[],NULL,true),
('turkish-coffee','brewing','Turkish Coffee','Turska kava','Finely ground coffee simmered with water, traditionally unfiltered.','Vrlo fino mljevena kava kuhana s vodom, tradicionalno nefiltrirana.','Finely ground coffee simmered with water, traditionally unfiltered. Typical values vary by café size and recipe.','Vrlo fino mljevena kava kuhana s vodom, tradicionalno nefiltrirana. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":7,"espresso_ml":0,"water_ml":70,"milk_ml":0,"foam_ml":0,"cup_ml":90,"caffeine_mg_min":50,"caffeine_mg_max":75,"calories_min":2,"calories_max":8}'::jsonb,ARRAY['turkish coffee','turska kava','cezve','ibrik']::text[],ARRAY['turkish coffee','turska kava','cezve','ibrik']::text[],NULL,true),
('filter-coffee','brewing','Filter Coffee','Filter kava','Hot water passes through ground coffee and a paper or metal filter.','Vruća voda prolazi kroz mljevenu kavu i papirnati ili metalni filter.','Hot water passes through ground coffee and a paper or metal filter. Typical values vary by café size and recipe.','Vruća voda prolazi kroz mljevenu kavu i papirnati ili metalni filter. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":15,"espresso_ml":0,"water_ml":250,"milk_ml":0,"foam_ml":0,"cup_ml":250,"caffeine_mg_min":80,"caffeine_mg_max":140,"calories_min":2,"calories_max":8}'::jsonb,ARRAY['filter coffee','drip coffee','batch brew']::text[],ARRAY['filter coffee','drip coffee','batch brew']::text[],NULL,true),
('v60','brewing','V60 Pour-over','V60 preljevna kava','Manual pour-over with a cone dripper, usually clean and aromatic.','Ručna preljevna metoda s konusnim dripperom, obično čista i aromatična.','Manual pour-over with a cone dripper, usually clean and aromatic. Typical values vary by café size and recipe.','Ručna preljevna metoda s konusnim dripperom, obično čista i aromatična. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":15,"espresso_ml":0,"water_ml":250,"milk_ml":0,"foam_ml":0,"cup_ml":250,"caffeine_mg_min":80,"caffeine_mg_max":140,"calories_min":2,"calories_max":8}'::jsonb,ARRAY['v60','pour over','hand brew']::text[],ARRAY['v60','pour over','hand brew']::text[],NULL,true),
('chemex','brewing','Chemex','Chemex','Pour-over brewed through a thick paper filter for a very clean cup.','Preljevna kava kroz deblji papirnati filter za vrlo čist okus.','Pour-over brewed through a thick paper filter for a very clean cup. Typical values vary by café size and recipe.','Preljevna kava kroz deblji papirnati filter za vrlo čist okus. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":30,"espresso_ml":0,"water_ml":500,"milk_ml":0,"foam_ml":0,"cup_ml":500,"caffeine_mg_min":120,"caffeine_mg_max":220,"calories_min":3,"calories_max":12}'::jsonb,ARRAY['chemex','pour over','filter']::text[],ARRAY['chemex','pour over','filter']::text[],NULL,true),
('french-press','brewing','French Press','French Press','Coffee steeps in hot water and is separated with a metal plunger.','Kava se namače u vrućoj vodi i odvaja metalnim klipom.','Coffee steeps in hot water and is separated with a metal plunger. Typical values vary by café size and recipe.','Kava se namače u vrućoj vodi i odvaja metalnim klipom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":0,"water_ml":300,"milk_ml":0,"foam_ml":0,"cup_ml":300,"caffeine_mg_min":90,"caffeine_mg_max":160,"calories_min":3,"calories_max":10}'::jsonb,ARRAY['french press','cafetiere','plunger']::text[],ARRAY['french press','cafetiere','plunger']::text[],NULL,true),
('moka-pot','brewing','Moka Pot','Moka pot','Stovetop brewer using steam pressure to make a strong coffee.','Kuhalo za štednjak koje koristi tlak pare za jaku kavu.','Stovetop brewer using steam pressure to make a strong coffee. Typical values vary by café size and recipe.','Kuhalo za štednjak koje koristi tlak pare za jaku kavu. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":18,"espresso_ml":0,"water_ml":120,"milk_ml":0,"foam_ml":0,"cup_ml":120,"caffeine_mg_min":80,"caffeine_mg_max":140,"calories_min":3,"calories_max":10}'::jsonb,ARRAY['moka pot','bialetti','stovetop coffee']::text[],ARRAY['moka pot','bialetti','stovetop coffee']::text[],NULL,true),
('hot-chocolate','tea','Hot Chocolate','Vruća čokolada','Milk-based chocolate drink; recipe and calories depend strongly on chocolate and sugar.','Čokoladni napitak na bazi mlijeka; recept i kalorije ovise o čokoladi i šećeru.','Milk-based chocolate drink; recipe and calories depend strongly on chocolate and sugar. Typical values vary by café size and recipe.','Čokoladni napitak na bazi mlijeka; recept i kalorije ovise o čokoladi i šećeru. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":0,"milk_ml":220,"foam_ml":10,"cup_ml":250,"caffeine_mg_min":0,"caffeine_mg_max":10,"calories_min":180,"calories_max":350}'::jsonb,ARRAY['hot chocolate','chocolate milk','cocoa']::text[],ARRAY['hot chocolate','chocolate milk','cocoa']::text[],'Contains milk unless ordered without dairy.',true),
('matcha-latte','tea','Matcha Latte','Matcha latte','Matcha whisked with a small amount of water and topped with milk.','Matcha umućena s malo vode i nadopunjena mlijekom.','Matcha whisked with a small amount of water and topped with milk. Typical values vary by café size and recipe.','Matcha umućena s malo vode i nadopunjena mlijekom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":2,"espresso_ml":0,"water_ml":50,"milk_ml":180,"foam_ml":10,"cup_ml":250,"caffeine_mg_min":25,"caffeine_mg_max":70,"calories_min":100,"calories_max":190}'::jsonb,ARRAY['matcha latte','green tea latte','matcha']::text[],ARRAY['matcha latte','green tea latte','matcha']::text[],'Contains milk unless ordered without dairy.',true),
('chai-latte','tea','Chai Latte','Chai latte','Spiced tea concentrate or infusion combined with steamed milk.','Začinjeni čajni koncentrat ili infuzija pomiješana s toplim mlijekom.','Spiced tea concentrate or infusion combined with steamed milk. Typical values vary by café size and recipe.','Začinjeni čajni koncentrat ili infuzija pomiješana s toplim mlijekom. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":80,"milk_ml":160,"foam_ml":10,"cup_ml":250,"caffeine_mg_min":20,"caffeine_mg_max":60,"calories_min":120,"calories_max":240}'::jsonb,ARRAY['chai latte','spiced tea','masala chai']::text[],ARRAY['chai latte','spiced tea','masala chai']::text[],'Contains milk unless ordered without dairy.',true),
('fruit-smoothie','smoothie','Fruit Smoothie','Voćni smoothie','Blended fruit with juice, water, yogurt or milk; exact nutrition depends on recipe.','Miksano voće sa sokom, vodom, jogurtom ili mlijekom; nutritivne vrijednosti ovise o receptu.','Blended fruit with juice, water, yogurt or milk; exact nutrition depends on recipe. Typical values vary by café size and recipe.','Miksano voće sa sokom, vodom, jogurtom ili mlijekom; nutritivne vrijednosti ovise o receptu. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":80,"milk_ml":0,"foam_ml":0,"cup_ml":350,"caffeine_mg_min":0,"caffeine_mg_max":5,"calories_min":140,"calories_max":320}'::jsonb,ARRAY['smoothie','fruit drink','blended fruit']::text[],ARRAY['smoothie','fruit drink','blended fruit']::text[],NULL,true),
('milkshake','smoothie','Milkshake','Milkshake','Milk blended with ice cream or flavor base; typically richer than a smoothie.','Mlijeko miksano sa sladoledom ili bazom okusa; obično bogatije od smoothija.','Milk blended with ice cream or flavor base; typically richer than a smoothie. Typical values vary by café size and recipe.','Mlijeko miksano sa sladoledom ili bazom okusa; obično bogatije od smoothija. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":0,"milk_ml":220,"foam_ml":0,"cup_ml":350,"caffeine_mg_min":0,"caffeine_mg_max":5,"calories_min":280,"calories_max":550}'::jsonb,ARRAY['milkshake','shake','ice cream drink']::text[],ARRAY['milkshake','shake','ice cream drink']::text[],'Contains milk unless ordered without dairy.',true),
('mocktail','mocktail','Mocktail','Mocktail','A mixed drink without alcohol, often using juice, syrup, soda, herbs and ice.','Miješano bezalkoholno piće, često od soka, sirupa, sode, bilja i leda.','A mixed drink without alcohol, often using juice, syrup, soda, herbs and ice. Typical values vary by café size and recipe.','Miješano bezalkoholno piće, često od soka, sirupa, sode, bilja i leda. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":200,"milk_ml":0,"foam_ml":0,"cup_ml":350,"caffeine_mg_min":0,"caffeine_mg_max":0,"calories_min":60,"calories_max":220}'::jsonb,ARRAY['mocktail','non alcoholic cocktail','virgin cocktail']::text[],ARRAY['mocktail','non alcoholic cocktail','virgin cocktail']::text[],NULL,true),
('cocktail','cocktail','Cocktail','Koktel','A mixed alcoholic drink. Exact strength and calories depend on the spirits and mixers used.','Miješano alkoholno piće. Jačina i kalorije ovise o alkoholu i mikserima.','A mixed alcoholic drink. Exact strength and calories depend on the spirits and mixers used. Typical values vary by café size and recipe.','Miješano alkoholno piće. Jačina i kalorije ovise o alkoholu i mikserima. Tipične vrijednosti ovise o veličini i receptu kafića.','{"coffee_g":0,"espresso_ml":0,"water_ml":100,"milk_ml":0,"foam_ml":0,"cup_ml":250,"caffeine_mg_min":0,"caffeine_mg_max":0,"calories_min":120,"calories_max":350}'::jsonb,ARRAY['cocktail','alcohol drink','mixed drink']::text[],ARRAY['cocktail','alcohol drink','mixed drink']::text[],NULL,true)
on conflict (slug) do update set category=excluded.category,name_en=excluded.name_en,name_hr=excluded.name_hr,summary_en=excluded.summary_en,summary_hr=excluded.summary_hr,details_en=excluded.details_en,details_hr=excluded.details_hr,recipe=excluded.recipe,keywords=excluded.keywords,aliases=excluded.aliases,allergen_note=excluded.allergen_note,active=excluded.active,updated_at=now();

create or replace function public.search_langar_knowledge_v540(p_question text,p_lang text default 'en') returns table(id uuid,slug text,category text,name_en text,name_hr text,summary_en text,summary_hr text,details_en text,details_hr text,recipe jsonb,keywords text[],aliases text[],allergen_note text,score numeric) language sql stable security definer set search_path=public as $$
with q as(select lower(trim(coalesce(p_question,''))) t), scored as(select k.*, greatest(similarity(lower(k.name_en),q.t),similarity(lower(k.name_hr),q.t),coalesce((select max(similarity(lower(x),q.t)) from unnest(k.aliases||k.keywords) x),0)) + case when q.t like '%'||lower(k.name_en)||'%' or q.t like '%'||lower(k.name_hr)||'%' then 1.2 else 0 end + coalesce((select count(*)*.18 from unnest(k.keywords||k.aliases) x where q.t like '%'||lower(x)||'%'),0) s from public.langar_knowledge_entries k,q where k.active) select id,slug,category,name_en,name_hr,summary_en,summary_hr,details_en,details_hr,recipe,keywords,aliases,allergen_note,round(s::numeric,3) from scored order by s desc limit 3;$$;
grant execute on function public.search_langar_knowledge_v540(text,text) to authenticated;

create or replace function public.smart_barista_ask_v540(p_question text,p_subject text default 'Drink question',p_lang text default 'en') returns jsonb language plpgsql security definer set search_path=public as $$declare u auth.users; k record; qid uuid; sensitive boolean; begin select * into u from auth.users where id=auth.uid(); if u.id is null then raise exception 'Authentication required'; end if; sensitive:=lower(p_question) ~ '(allerg|alerg|anaphyl|celiac|gluten|diabet|pregnan|medical|medicine|lijek|trudn|šećer|secer)'; select * into k from public.search_langar_knowledge_v540(p_question,p_lang) limit 1; if not sensitive and k.id is not null and k.score>=0.62 then insert into public.barista_questions(user_id,customer_email,subject,question,status,admin_reply,answer_source,matched_knowledge_id,answered_at,created_at) values(u.id,u.email,p_subject,p_question,'answered',case when p_lang='hr' then k.summary_hr||E'

'||coalesce(k.details_hr,'') else k.summary_en||E'

'||coalesce(k.details_en,'') end,'knowledge',k.id,now(),now()) returning id into qid; return jsonb_build_object('matched',true,'question_id',qid,'knowledge',to_jsonb(k)); else insert into public.barista_questions(user_id,customer_email,subject,question,status,answer_source,created_at) values(u.id,u.email,p_subject,p_question,'new','human',now()) returning id into qid; return jsonb_build_object('matched',false,'question_id',qid,'sensitive',sensitive); end if; end$$;
grant execute on function public.smart_barista_ask_v540(text,text,text) to authenticated;

create or replace function public.list_my_barista_questions_v540() returns table(id uuid,subject text,question text,status text,admin_reply text,answer_source text,created_at timestamptz,answered_at timestamptz) language sql stable security definer set search_path=public as $$select b.id,b.subject,b.question,b.status,b.admin_reply,b.answer_source,b.created_at,b.answered_at from public.barista_questions b where b.user_id=auth.uid() or lower(b.customer_email)=lower(coalesce(auth.jwt()->>'email','')) order by b.created_at desc limit 100$$;
grant execute on function public.list_my_barista_questions_v540() to authenticated;

create or replace function public.admin_list_knowledge_v540(p_search text default null,p_category text default null) returns setof public.langar_knowledge_entries language sql stable security definer set search_path=public as $$select * from public.langar_knowledge_entries k where (p_category is null or p_category='' or k.category=p_category) and (p_search is null or p_search='' or k.name_en ilike '%'||p_search||'%' or k.name_hr ilike '%'||p_search||'%' or exists(select 1 from unnest(k.keywords||k.aliases) x where x ilike '%'||p_search||'%')) order by k.category,k.name_en$$;
grant execute on function public.admin_list_knowledge_v540(text,text) to authenticated;
