-- Langar Bar V5.4.1 Knowledge Reliability + 50 Suggested Questions
create extension if not exists unaccent;

create table if not exists public.langar_knowledge_faqs (
 id uuid primary key default gen_random_uuid(),
 slug text unique not null,
 category text not null,
 question_en text not null,
 question_hr text not null,
 answer_en text not null,
 answer_hr text not null,
 keywords text[] not null default '{}',
 active boolean not null default true,
 sort_order integer not null default 100,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

insert into public.langar_knowledge_faqs(slug,category,question_en,question_hr,answer_en,answer_hr,keywords,active)
values
('cappuccino-milk','milk-coffee','How much milk is in a cappuccino?','Koliko mlijeka ima cappuccino?','A standard 150–180 ml cappuccino usually contains about 60–90 ml steamed milk plus roughly 30–60 ml microfoam, with one espresso shot. Langar Bar’s published house recipe takes priority.','Standardni cappuccino od 150–180 ml obično sadrži oko 60–90 ml toplog mlijeka i približno 30–60 ml mikropjene, uz jednu dozu espressa. Prednost ima objavljeni recept Langar Bara.',ARRAY['cappuccino','milk','ml','foam']::text[],true),
('latte-vs-cappuccino','comparison','What is the difference between latte and cappuccino?','Koja je razlika između lattea i cappuccina?','A latte contains more steamed milk and only a thin microfoam layer, so it tastes milder. A cappuccino is smaller, has less milk and a thicker foam layer, so the coffee flavour is more pronounced.','Latte sadrži više toplog mlijeka i samo tanki sloj mikropjene pa je blažeg okusa. Cappuccino je manji, ima manje mlijeka i deblji sloj pjene pa je okus kave izraženiji.',ARRAY['latte','cappuccino','difference','foam','milk']::text[],true),
('flat-white-vs-latte','comparison','What is the difference between flat white and latte?','Koja je razlika između flat whitea i lattea?','Flat white is normally smaller, often uses two espresso shots and has a very thin silky microfoam. Latte is larger, milkier and milder.','Flat white je obično manji, često ima dvije doze espressa i vrlo tanku svilenkastu mikropjenu. Latte je veći, mliječniji i blaži.',ARRAY['flat white','latte','difference']::text[],true),
('coffee-caffeine','caffeine','How much caffeine is in coffee?','Koliko kofeina ima kava?','Caffeine varies by bean, dose and extraction. One espresso commonly contains about 55–80 mg; a double espresso about 110–160 mg. Filter coffee can contain more per cup because the serving is larger.','Količina kofeina ovisi o zrnu, dozi i ekstrakciji. Jedan espresso često ima oko 55–80 mg, a dvostruki 110–160 mg. Filter kava može imati više po šalici jer je porcija veća.',ARRAY['caffeine','espresso','filter coffee']::text[],true),
('decaf','caffeine','Which coffee has no caffeine?','Koja kava nema kofeina?','Decaffeinated coffee has most caffeine removed, but it is not always completely caffeine-free. A cup typically retains a small amount. Herbal infusions are naturally caffeine-free unless blended with tea or coffee.','Bezkofeinskoj kavi uklonjena je većina kofeina, ali nije uvijek potpuno bez kofeina. U šalici obično ostaje mala količina. Biljne infuzije prirodno su bez kofeina ako nisu pomiješane s čajem ili kavom.',ARRAY['decaf','no caffeine','caffeine free']::text[],true),
('best-time-coffee','wellbeing','When is the best time to drink coffee?','Kada je najbolje piti kavu?','Many people tolerate coffee best earlier in the day. Because caffeine can affect sleep for several hours, consider avoiding it about 6–8 hours before bedtime if you are sensitive. Individual response varies.','Mnogima kava najbolje odgovara ranije tijekom dana. Budući da kofein može utjecati na san više sati, ako ste osjetljivi razmislite o izbjegavanju kave 6–8 sati prije spavanja. Reakcije su individualne.',ARRAY['best time','sleep','morning','coffee']::text[],true),
('coffee-empty-stomach','wellbeing','Can I drink coffee on an empty stomach?','Mogu li piti kavu na prazan želudac?','Many people can, but some experience heartburn, nausea or discomfort. If that happens, drink it with food, choose a milder drink or speak with a healthcare professional for persistent symptoms.','Mnogi mogu, ali neki osjećaju žgaravicu, mučninu ili nelagodu. Ako se to događa, pijte je uz hranu, odaberite blaži napitak ili se za trajne simptome obratite zdravstvenom stručnjaku.',ARRAY['empty stomach','food','heartburn']::text[],true),
('coffee-with-water','serving','Why is water served with coffee?','Zašto se uz kavu poslužuje voda?','Water refreshes the palate and helps you taste the coffee more clearly. It is usually best sipped before tasting the coffee, though there is no strict rule.','Voda osvježava nepce i pomaže jasnije osjetiti okus kave. Obično se pije prije kušanja kave, iako ne postoji strogo pravilo.',ARRAY['water','served','palate']::text[],true),
('espresso-origin','history','Where did espresso originate?','Odakle potječe espresso?','Espresso developed in Italy around the turn of the 20th century as inventors sought a faster way to brew coffee for urban cafés. Early steam machines were followed by pressure-based machines that shaped modern espresso.','Espresso se razvio u Italiji početkom 20. stoljeća kada su izumitelji tražili brži način pripreme kave za gradske kavane. Rane parne strojeve kasnije su zamijenili tlačni aparati koji su oblikovali moderni espresso.',ARRAY['espresso','origin','history','italy']::text[],true),
('coffee-origin','history','Where did coffee originate?','Odakle potječe kava?','Coffee’s plant origins are associated with Ethiopia, while the earliest well-documented coffee drinking and cultivation traditions developed in Yemen. From there coffee spread through the Ottoman world and into Europe.','Podrijetlo biljke kave povezuje se s Etiopijom, dok su se najranije dobro dokumentirane tradicije pijenja i uzgoja kave razvile u Jemenu. Odatle se kava proširila Osmanskim Carstvom i Europom.',ARRAY['coffee','origin','ethiopia','yemen','history']::text[],true),
('arabica-vs-robusta','beans','What is the difference between Arabica and Robusta?','Koja je razlika između Arabice i Robuste?','Arabica is generally more aromatic, sweeter and more acidic, while Robusta usually has more caffeine, a heavier body and more bitterness. Quality depends on origin, processing and roasting, not species alone.','Arabica je općenito aromatičnija, slađa i kiselija, dok Robusta obično ima više kofeina, punije tijelo i više gorčine. Kvaliteta ovisi o podrijetlu, obradi i prženju, ne samo o vrsti.',ARRAY['arabica','robusta','beans','difference']::text[],true),
('espresso-vs-filter','comparison','What is the difference between espresso and filter coffee?','Koja je razlika između espressa i filter kave?','Espresso is concentrated and brewed quickly under pressure. Filter coffee uses gravity and a longer contact time. Espresso has more caffeine per millilitre, but a full filter cup may contain more total caffeine.','Espresso je koncentriran i brzo se priprema pod pritiskom. Filter kava koristi gravitaciju i dulji kontakt s vodom. Espresso ima više kofeina po mililitru, ali puna šalica filter kave može imati više ukupnog kofeina.',ARRAY['espresso','filter','difference']::text[],true),
('americano-vs-filter','comparison','Is Americano the same as filter coffee?','Je li Americano isto što i filter kava?','No. Americano is espresso diluted with hot water. Filter coffee is brewed by passing water through ground coffee and a filter, producing a different aroma, body and extraction profile.','Ne. Americano je espresso razrijeđen vrućom vodom. Filter kava priprema se prolaskom vode kroz mljevenu kavu i filter, pa ima drugačiju aromu, tijelo i profil ekstrakcije.',ARRAY['americano','filter coffee','same']::text[],true),
('ristretto-vs-espresso','comparison','What is the difference between ristretto and espresso?','Koja je razlika između ristretta i espressa?','Ristretto uses a similar coffee dose but a shorter beverage yield. It is smaller and more concentrated, often with less perceived bitterness. Espresso has a longer yield and broader flavour balance.','Ristretto koristi sličnu dozu kave, ali kraći izlaz napitka. Manji je i koncentriraniji, često s manje doživljene gorčine. Espresso ima dulji izlaz i širu ravnotežu okusa.',ARRAY['ristretto','espresso','difference']::text[],true),
('lungo-vs-americano','comparison','What is the difference between lungo and Americano?','Koja je razlika između lunga i Americana?','Lungo is extracted longer through the coffee bed. Americano is a normal espresso with water added afterward. Because extraction differs, their bitterness, body and aroma are not the same.','Lungo se dulje ekstrahira kroz sloj kave. Americano je normalan espresso kojem se naknadno dodaje voda. Zbog različite ekstrakcije razlikuju se gorčina, tijelo i aroma.',ARRAY['lungo','americano','difference']::text[],true),
('macchiato','milk-coffee','What is an espresso macchiato?','Što je espresso macchiato?','Espresso macchiato means an espresso ‘marked’ with a small amount of milk or foam—usually only about 5–20 ml. It remains a strong, small coffee drink.','Espresso macchiato znači espresso ''obilježen'' malom količinom mlijeka ili pjene—obično oko 5–20 ml. I dalje je snažan i mali napitak.',ARRAY['macchiato','milk','foam']::text[],true),
('cortado','milk-coffee','What is a cortado?','Što je cortado?','Cortado is espresso softened with roughly an equal amount of warm milk and very little foam. It is smaller and more coffee-forward than a latte.','Cortado je espresso ublažen približno jednakom količinom toplog mlijeka i vrlo malo pjene. Manji je i okus kave je izraženiji nego u latteu.',ARRAY['cortado','milk']::text[],true),
('mocha','milk-coffee','What is a mocha?','Što je mocha?','A café mocha combines espresso, chocolate and milk, often with a small layer of foam or whipped cream. It is sweeter and usually higher in calories than a plain latte.','Café mocha spaja espresso, čokoladu i mlijeko, često s malo pjene ili šlaga. Slađa je i obično kaloričnija od običnog lattea.',ARRAY['mocha','chocolate','milk']::text[],true),
('affogato','dessert','What is affogato?','Što je affogato?','Affogato is a dessert made by pouring hot espresso over a scoop of vanilla gelato or ice cream. It combines hot, bitter coffee with cold, sweet creaminess.','Affogato je desert u kojem se vrući espresso prelije preko kuglice sladoleda od vanilije. Spaja vruću, gorkastu kavu s hladnom, slatkom kremoznošću.',ARRAY['affogato','ice cream','dessert']::text[],true),
('cold-brew-vs-iced','cold-coffee','What is the difference between cold brew and iced coffee?','Koja je razlika između cold brewa i ledene kave?','Cold brew is extracted with cool water for many hours. Iced coffee is normally brewed hot and chilled over ice. Cold brew is often smoother and less sharp, while iced coffee keeps more hot-brew aroma.','Cold brew se ekstrahira hladnom vodom mnogo sati. Ledena kava obično se priprema vruća i hladi preko leda. Cold brew je često glađi i manje oštar, dok ledena kava zadržava više arome vruće ekstrakcije.',ARRAY['cold brew','iced coffee','difference']::text[],true),
('iced-latte','cold-coffee','What is in an iced latte?','Što sadrži iced latte?','Iced latte normally contains espresso, cold milk and ice. A common 300–400 ml serving uses one or two espresso shots and roughly 180–250 ml milk, depending on the house recipe.','Iced latte obično sadrži espresso, hladno mlijeko i led. Uobičajena porcija od 300–400 ml koristi jednu ili dvije doze espressa i približno 180–250 ml mlijeka, ovisno o receptu kuće.',ARRAY['iced latte','milk','ice']::text[],true),
('espresso-tonic','cold-coffee','What is espresso tonic?','Što je espresso tonic?','Espresso tonic combines tonic water, ice and espresso. It is sparkling, bittersweet and citrus-like. The espresso is usually poured gently over the tonic to create layers.','Espresso tonic spaja tonic vodu, led i espresso. Pjenušav je, gorko-sladak i citrusan. Espresso se obično nježno ulijeva preko tonica kako bi se stvorili slojevi.',ARRAY['espresso tonic','tonic']::text[],true),
('turkish-coffee','brewing','What is Turkish coffee?','Što je turska kava?','Turkish coffee is made from very finely ground coffee simmered with water, often with sugar, and served unfiltered. The grounds settle at the bottom and should not be drunk.','Turska kava priprema se od vrlo fino mljevene kave kuhane s vodom, često i sa šećerom, te se poslužuje nefiltrirana. Talog se slegne na dno i ne pije se.',ARRAY['turkish coffee','unfiltered','grounds']::text[],true),
('french-press','brewing','How is French press coffee made?','Kako se priprema French press kava?','Coarsely ground coffee steeps in hot water, commonly for about four minutes, and is then separated with a metal mesh plunger. The method retains more oils and produces a fuller body.','Grubo mljevena kava namače se u vrućoj vodi, često oko četiri minute, a zatim se odvaja metalnim klipom. Metoda zadržava više ulja i daje punije tijelo.',ARRAY['french press','brew','plunger']::text[],true),
('v60','brewing','What is V60 coffee?','Što je V60 kava?','V60 is a cone-shaped pour-over method using a paper filter. Water is poured in controlled stages, producing a clean cup that highlights aroma, acidity and origin character.','V60 je konusna pour-over metoda s papirnatim filterom. Voda se ulijeva u kontroliranim fazama, što daje čistu šalicu koja ističe aromu, kiselost i karakter podrijetla.',ARRAY['v60','pour over','filter']::text[],true),
('chemex','brewing','What is Chemex coffee?','Što je Chemex kava?','Chemex is a pour-over brewer with a thick paper filter. It removes more oils and fine particles, producing a very clean, light and tea-like cup.','Chemex je pour-over aparat s debelim papirnatim filterom. Uklanja više ulja i sitnih čestica te daje vrlo čistu, laganu šalicu nalik čaju.',ARRAY['chemex','filter','pour over']::text[],true),
('aeropress','brewing','What is AeroPress?','Što je AeroPress?','AeroPress is a compact manual brewer that combines immersion and gentle pressure. It supports many recipes, from short concentrated coffee to longer filter-style cups.','AeroPress je kompaktan ručni aparat koji kombinira uranjanje i blagi pritisak. Omogućuje mnogo recepata, od kratke koncentrirane kave do duljih filter napitaka.',ARRAY['aeropress','brewer']::text[],true),
('moka-pot','brewing','Is moka pot coffee espresso?','Je li moka kava espresso?','Moka pot coffee is strong and concentrated, but it is not true espresso because it uses much lower pressure than an espresso machine.','Moka kava je snažna i koncentrirana, ali nije pravi espresso jer koristi znatno niži tlak od espresso aparata.',ARRAY['moka pot','espresso','bialetti']::text[],true),
('coffee-calories','nutrition','How many calories are in black coffee?','Koliko kalorija ima crna kava?','Plain espresso, Americano and filter coffee contain very few calories—often roughly 2–10 kcal per serving. Milk, sugar, syrup, cream and chocolate can raise the total substantially.','Obični espresso, Americano i filter kava imaju vrlo malo kalorija—često približno 2–10 kcal po porciji. Mlijeko, šećer, sirup, vrhnje i čokolada mogu znatno povećati ukupnu vrijednost.',ARRAY['calories','black coffee','nutrition']::text[],true),
('latte-calories','nutrition','How many calories are in a latte?','Koliko kalorija ima latte?','Calories depend on cup size and milk. A typical unsweetened 240–300 ml latte with dairy milk is often around 110–190 kcal. Syrups and cream add more.','Kalorije ovise o veličini i mlijeku. Tipični nezaslađeni latte od 240–300 ml s kravljim mlijekom često ima oko 110–190 kcal. Sirupi i vrhnje povećavaju vrijednost.',ARRAY['latte','calories','milk']::text[],true),
('plant-milk','milk','Can coffee be made with plant milk?','Može li se kava pripremiti s biljnim mlijekom?','Yes, when available. Oat, soy, almond and coconut drinks behave differently when steamed. Oat and barista-style soy often create the most stable microfoam. Always check allergens and the actual Langar Bar options.','Da, ako je dostupno. Zobeni, sojin, bademov i kokosov napitak različito se ponašaju pri pjenjenju. Zobeni i barista sojin često daju najstabilniju mikropjenu. Uvijek provjerite alergene i stvarnu ponudu Langar Bara.',ARRAY['plant milk','oat','soy','almond']::text[],true),
('lactose-free','milk','Is lactose-free milk dairy-free?','Je li mlijeko bez laktoze bez mliječnih sastojaka?','No. Lactose-free milk is still cow’s milk; the lactose has been broken down or removed. It still contains milk proteins and is not suitable for a milk-protein allergy.','Ne. Mlijeko bez laktoze i dalje je kravlje mlijeko; laktoza je razgrađena ili uklonjena. I dalje sadrži mliječne proteine i nije prikladno kod alergije na mliječne proteine.',ARRAY['lactose free','dairy','allergy']::text[],true),
('coffee-strength','taste','Which coffee tastes strongest?','Koja kava ima najjači okus?','For a strong coffee-forward taste, ristretto, espresso, doppio, macchiato or flat white are common choices. ‘Strong taste’ is not exactly the same as total caffeine.','Za snažan okus kave česti su izbor ristretto, espresso, doppio, macchiato ili flat white. ''Jak okus'' nije isto što i ukupna količina kofeina.',ARRAY['strongest','strong coffee','taste']::text[],true),
('mild-coffee','taste','Which coffee is mild and not bitter?','Koja je kava blaga i nije gorka?','Latte, cappuccino with balanced espresso, or a light-roasted filter coffee can taste milder. Milk softens bitterness, while good extraction and fresh coffee improve balance.','Latte, uravnotežen cappuccino ili filter kava svjetlijeg prženja mogu biti blaži. Mlijeko ublažava gorčinu, a dobra ekstrakcija i svježa kava poboljšavaju ravnotežu.',ARRAY['mild','not bitter','coffee']::text[],true),
('coffee-bitter','taste','Why does coffee taste bitter?','Zašto je kava gorka?','Bitterness can come from dark roasting, over-extraction, too-fine grinding, water that is too hot or stale coffee. Some bitterness is natural, but harsh bitterness often signals imbalance.','Gorčina može dolaziti od tamnog prženja, preduge ekstrakcije, presitnog mljevenja, prevruće vode ili ustajale kave. Dio gorčine je prirodan, ali oštra gorčina često znači neravnotežu.',ARRAY['bitter','over extraction','grind']::text[],true),
('coffee-sour','taste','Why does coffee taste sour?','Zašto je kava kisela?','Sharp sourness may indicate under-extraction, coffee ground too coarsely, water that is too cool or too short a brew time. Pleasant fruit-like acidity, however, can be a natural quality of specialty coffee.','Oštra kiselost može značiti nedovoljnu ekstrakciju, pregrubo mljevenje, prenisku temperaturu vode ili prekratko vrijeme. Ugodna voćna kiselost ipak može biti prirodna kvaliteta specialty kave.',ARRAY['sour','acidic','under extraction']::text[],true),
('coffee-freshness','storage','How should coffee beans be stored?','Kako čuvati zrna kave?','Store beans sealed, dry, away from heat, light, moisture and strong odours. Grind shortly before brewing. Avoid repeatedly opening a large container; smaller airtight portions are better.','Zrna čuvajte zatvorena, suha, dalje od topline, svjetla, vlage i jakih mirisa. Meljite neposredno prije pripreme. Bolje su manje hermetičke porcije nego često otvaranje velike posude.',ARRAY['store beans','freshness','storage']::text[],true),
('coffee-fridge','storage','Should coffee be stored in the refrigerator?','Treba li kavu čuvati u hladnjaku?','Usually not for daily use, because coffee absorbs moisture and odours. An airtight freezer portion can work for longer storage, but avoid repeated thawing and refreezing.','Obično ne za svakodnevnu uporabu jer kava upija vlagu i mirise. Hermetički zatvorena porcija u zamrzivaču može poslužiti za dulje čuvanje, ali izbjegavajte višestruko odmrzavanje i ponovno zamrzavanje.',ARRAY['fridge','freezer','coffee storage']::text[],true),
('coffee-roast','beans','What is the difference between light and dark roast?','Koja je razlika između svijetlog i tamnog prženja?','Light roasts often preserve more origin character, fruit and acidity. Dark roasts develop more roast, cocoa and smoky notes, with lower perceived acidity. Darker does not automatically mean more caffeine.','Svjetlije prženje često čuva više karaktera podrijetla, voćnosti i kiselosti. Tamnije razvija više prženih, kakao i dimnih nota uz manju doživljenu kiselost. Tamnije ne znači automatski više kofeina.',ARRAY['light roast','dark roast','roast']::text[],true),
('crema','espresso','What is espresso crema?','Što je espresso crema?','Crema is the golden-brown foam formed by gases, oils and fine particles during espresso extraction. It can indicate freshness and extraction, but crema alone does not prove quality.','Crema je zlatno-smeđa pjena nastala od plinova, ulja i sitnih čestica tijekom ekstrakcije espressa. Može ukazivati na svježinu i ekstrakciju, ali sama crema ne dokazuje kvalitetu.',ARRAY['crema','espresso foam']::text[],true),
('microfoam','milk-coffee','What is microfoam?','Što je mikropjena?','Microfoam is milk textured with very small, uniform bubbles. It feels glossy and silky, integrates with espresso and is essential for smooth cappuccino, flat white and latte art.','Mikropjena je mlijeko teksturirano vrlo sitnim i ujednačenim mjehurićima. Sjajna je i svilenkasta, spaja se s espressom i ključna je za cappuccino, flat white i latte art.',ARRAY['microfoam','milk foam','latte art']::text[],true),
('matcha','tea','What is matcha latte?','Što je matcha latte?','Matcha latte combines finely ground green tea with a small amount of water and milk. It contains caffeine, but the amount varies with the dose and is often lower than a double espresso.','Matcha latte spaja fino mljeveni zeleni čaj s malo vode i mlijekom. Sadrži kofein, ali količina ovisi o dozi i često je niža od dvostrukog espressa.',ARRAY['matcha','green tea','caffeine']::text[],true),
('chai','tea','What is chai latte?','Što je chai latte?','Chai latte is spiced tea—often black tea with cinnamon, cardamom, ginger and cloves—combined with milk. It may contain caffeine and sugar depending on the base.','Chai latte je začinjeni čaj—često crni čaj s cimetom, kardamomom, đumbirom i klinčićem—pomiješan s mlijekom. Može sadržavati kofein i šećer ovisno o bazi.',ARRAY['chai latte','spices','tea']::text[],true),
('smoothie-definition','smoothie','What is a smoothie?','Što je smoothie?','A smoothie is a thick blended drink made mainly from whole fruit or vegetables, often with juice, milk, yogurt, water or ice. Unlike clear juice, it usually retains more fruit fibre.','Smoothie je gusti miksani napitak uglavnom od cijelog voća ili povrća, često sa sokom, mlijekom, jogurtom, vodom ili ledom. Za razliku od bistrog soka, obično zadržava više vlakana.',ARRAY['smoothie','definition','fruit']::text[],true),
('smoothie-vs-juice','comparison','What is the difference between smoothie and juice?','Koja je razlika između smoothija i soka?','Smoothies blend whole ingredients and normally retain more fibre. Juice removes much of the pulp and is thinner. Calories and sugar still depend on ingredients and portion size.','Smoothie miksanjem koristi cijele sastojke i obično zadržava više vlakana. Sok uklanja velik dio pulpe i rjeđi je. Kalorije i šećer ipak ovise o sastojcima i veličini porcije.',ARRAY['smoothie','juice','difference']::text[],true),
('frappe-definition','cold-drink','What is a frappe?','Što je frappe?','‘Frappe’ describes a cold shaken or blended drink, but recipes vary by country. It may be instant coffee shaken with water and ice, or a blended café drink with milk, syrup and sometimes ice cream.','''Frappe'' opisuje hladni protreseni ili miksani napitak, ali recepti se razlikuju po zemljama. Može biti instant kava protresena s vodom i ledom ili miksani napitak s mlijekom, sirupom i ponekad sladoledom.',ARRAY['frappe','cold coffee','definition']::text[],true),
('mocktail-definition','mocktail','What is a mocktail?','Što je mocktail?','A mocktail is a mixed drink without alcohol. It can include fruit juice, syrup, soda, tonic, herbs, spices, citrus and ice, prepared with the presentation of a cocktail.','Mocktail je miješano piće bez alkohola. Može sadržavati voćni sok, sirup, sodu, tonic, bilje, začine, citruse i led, uz prezentaciju koktela.',ARRAY['mocktail','alcohol free','definition']::text[],true),
('cocktail-definition','cocktail','What is a cocktail?','Što je koktel?','A cocktail is a mixed alcoholic drink made from one or more spirits plus ingredients such as juice, syrup, bitters, soda or herbs. Strength and calories vary widely by recipe.','Koktel je miješano alkoholno piće od jednog ili više žestokih pića te sastojaka poput soka, sirupa, bittera, sode ili bilja. Jačina i kalorije jako ovise o receptu.',ARRAY['cocktail','alcohol','definition']::text[],true),
('mocktail-vs-cocktail','comparison','What is the difference between mocktail and cocktail?','Koja je razlika između mocktaila i koktela?','A cocktail contains alcohol; a mocktail does not. Both can use similar mixing techniques, glassware, garnish and flavour balance.','Koktel sadrži alkohol, a mocktail ne. Oba mogu koristiti slične tehnike miješanja, čaše, ukrase i ravnotežu okusa.',ARRAY['mocktail','cocktail','difference']::text[],true),
('milkshake-vs-smoothie','comparison','What is the difference between milkshake and smoothie?','Koja je razlika između milkshakea i smoothija?','Milkshake is usually based on milk and ice cream or a dessert flavour base, making it richer. Smoothie is usually based on blended fruit or vegetables and may include yogurt, milk or juice.','Milkshake se obično temelji na mlijeku i sladoledu ili desertnoj bazi pa je bogatiji. Smoothie se obično temelji na miksanom voću ili povrću te može sadržavati jogurt, mlijeko ili sok.',ARRAY['milkshake','smoothie','difference']::text[],true),
('coffee-after-meal','serving','Why do people drink espresso after a meal?','Zašto ljudi piju espresso nakon obroka?','In many cultures espresso after a meal is a social and sensory tradition. It provides a short, intense finish. It does not replace medical digestive advice, and caffeine may not suit everyone late in the day.','U mnogim kulturama espresso nakon obroka društvena je i osjetilna tradicija. Daje kratak i intenzivan završetak. Ne zamjenjuje medicinski savjet o probavi, a kofein nekima ne odgovara kasno u danu.',ARRAY['after meal','espresso','digest']::text[],true),
('coffee-pairing','serving','What food goes well with coffee?','Koja hrana dobro ide uz kavu?','Espresso pairs well with small sweet bites; cappuccino and latte with croissants, cakes and breakfast; filter coffee with pastries or fruit desserts. Pairing depends on roast and flavour—nutty coffees suit chocolate, while fruity coffees suit berries and citrus.','Espresso se dobro slaže s malim slatkim zalogajima; cappuccino i latte s kroasanima, kolačima i doručkom; filter kava s pecivima ili voćnim desertima. Slaganje ovisi o prženju i okusu—orašaste kave idu uz čokoladu, a voćne uz bobičasto voće i citruse.',ARRAY['pairing','food','coffee']::text[],true),
('coffee-sugar','nutrition','Is it better to drink coffee without sugar?','Je li bolje piti kavu bez šećera?','Coffee without added sugar has fewer calories and lets you taste the bean and extraction more clearly. Whether to add sugar is a personal choice; gradually reducing it can help you notice natural sweetness.','Kava bez dodanog šećera ima manje kalorija i jasnije pokazuje okus zrna i ekstrakcije. Dodavanje šećera osobni je izbor; postupno smanjivanje može pomoći da osjetite prirodnu slatkoću.',ARRAY['sugar','coffee','calories']::text[],true),
('coffee-hydration','wellbeing','Does coffee dehydrate you?','Dehidrira li kava?','Coffee contributes to daily fluid intake. Caffeine has a mild diuretic effect, especially in people not accustomed to it, but normal moderate coffee intake generally does not cause dehydration by itself.','Kava doprinosi dnevnom unosu tekućine. Kofein ima blag diuretički učinak, osobito kod osoba koje nisu navikle, ali normalan umjeren unos kave sam po sebi uglavnom ne uzrokuje dehidraciju.',ARRAY['dehydrate','hydration','coffee']::text[],true),
('coffee-pregnancy','sensitive','Can I drink coffee during pregnancy?','Smijem li piti kavu u trudnoći?','This is a health-related question. Caffeine recommendations in pregnancy depend on medical guidance and total daily intake. Please consult your doctor or pharmacist; Langar Bar staff can help identify decaf and lower-caffeine options but cannot provide medical advice.','Ovo je zdravstveno pitanje. Preporuke za kofein u trudnoći ovise o medicinskim smjernicama i ukupnom dnevnom unosu. Obratite se liječniku ili ljekarniku; osoblje Langar Bara može pomoći pronaći bezkofeinske i slabije opcije, ali ne može davati medicinske savjete.',ARRAY['pregnancy','caffeine','medical']::text[],true),
('allergy-policy','sensitive','Can you guarantee a drink is allergen-free?','Možete li jamčiti da je napitak bez alergena?','We can provide the recorded ingredients and allergens, but we cannot guarantee absence of cross-contact in a working café unless a specific controlled procedure is confirmed. For a severe allergy, speak directly with staff before ordering.','Možemo navesti zabilježene sastojke i alergene, ali ne možemo jamčiti izostanak križnog kontakta u aktivnom kafiću bez potvrđenog kontroliranog postupka. Kod teške alergije razgovarajte izravno s osobljem prije narudžbe.',ARRAY['allergy','allergen free','cross contact']::text[],true)
on conflict (slug) do update set category=excluded.category,question_en=excluded.question_en,question_hr=excluded.question_hr,answer_en=excluded.answer_en,answer_hr=excluded.answer_hr,keywords=excluded.keywords,active=excluded.active,updated_at=now();

-- Correct the standard cappuccino recipe: added water is normally zero.
update public.langar_knowledge_entries
set recipe=jsonb_set(coalesce(recipe,'{}'::jsonb),'{water_ml}','0'::jsonb,true),updated_at=now()
where slug='cappuccino';

create or replace function public.langar_normalize_v541(p text)
returns text language sql stable as $$
 select trim(regexp_replace(lower(unaccent(coalesce(p,''))),'[^a-z0-9čćžšđ]+',' ','g'))
$$;

create or replace function public.find_knowledge_entry_v541(p_question text)
returns setof public.langar_knowledge_entries language sql stable security definer set search_path=public as $$
with q as (select public.langar_normalize_v541(p_question) t), ranked as (
 select k.*,
   (case when q.t like '%'||public.langar_normalize_v541(k.name_en)||'%' then 20 else 0 end)+
   (case when q.t like '%'||public.langar_normalize_v541(k.name_hr)||'%' then 20 else 0 end)+
   coalesce((select count(*)*5 from unnest(k.aliases||k.keywords) x where length(public.langar_normalize_v541(x))>2 and q.t like '%'||public.langar_normalize_v541(x)||'%'),0)+
   greatest(similarity(public.langar_normalize_v541(k.name_en),q.t),similarity(public.langar_normalize_v541(k.name_hr),q.t))*3 score
 from public.langar_knowledge_entries k,q where k.active
) select (r).* from ranked r where r.score>0 order by r.score desc,r.name_en limit 1
$$;
grant execute on function public.find_knowledge_entry_v541(text) to authenticated;

create or replace function public.find_knowledge_faq_v541(p_question text,p_lang text default 'en')
returns setof public.langar_knowledge_faqs language sql stable security definer set search_path=public as $$
with q as(select public.langar_normalize_v541(p_question) t), ranked as(
 select f.*,
   (case when similarity(public.langar_normalize_v541(case when p_lang='hr' then f.question_hr else f.question_en end),q.t)>.42 then 12 else 0 end)+
   coalesce((select count(*)*4 from unnest(f.keywords) x where length(public.langar_normalize_v541(x))>2 and q.t like '%'||public.langar_normalize_v541(x)||'%'),0)+
   greatest(similarity(public.langar_normalize_v541(f.question_en),q.t),similarity(public.langar_normalize_v541(f.question_hr),q.t))*5 score
 from public.langar_knowledge_faqs f,q where f.active
) select (r).* from ranked r where r.score>=4 order by r.score desc,r.sort_order,r.question_en limit 1
$$;
grant execute on function public.find_knowledge_faq_v541(text,text) to authenticated;

create or replace function public.smart_barista_ask_v541(p_question text,p_subject text default 'Drink question',p_lang text default 'en')
returns jsonb language plpgsql security definer set search_path=public as $$
declare u auth.users; k public.langar_knowledge_entries; f public.langar_knowledge_faqs; qid uuid; sensitive boolean; t text; ans text; r jsonb;
begin
 select * into u from auth.users where id=auth.uid(); if u.id is null then raise exception 'Authentication required'; end if;
 t:=public.langar_normalize_v541(p_question);
 sensitive:=t ~ '(allerg|alerg|anaphyl|celiac|gluten|diabet|pregnan|trudn|medical|medicine|lijek|secer|šećer|blood pressure|heart condition)';
 select * into f from public.find_knowledge_faq_v541(p_question,p_lang) limit 1;
 select * into k from public.find_knowledge_entry_v541(p_question) limit 1;
 if sensitive and (f.id is null or f.category<>'sensitive') then
   insert into public.barista_questions(user_id,customer_email,subject,question,status,answer_source,created_at,updated_at)
   values(u.id,u.email,p_subject,p_question,'new','human',now(),now()) returning id into qid;
   return jsonb_build_object('matched',false,'question_id',qid,'sensitive',true);
 end if;
 if k.id is not null and (t ~ '(milk|mlijeko|foam|pjena|water|voda|coffee dose|doza|espresso|calorie|kalor|caffeine|kofein|cup|salic|šalic|how much|koliko)') then
   if t ~ '(milk|mlijeko)' then ans:=format('%s typically contains about %s ml milk and %s ml foam in a %s ml serving. Recipe values can vary; the published Langar Bar house recipe takes priority.',k.name_en,coalesce(k.recipe->>'milk_ml','0'),coalesce(k.recipe->>'foam_ml','0'),coalesce(k.recipe->>'cup_ml','—'));
   elsif t ~ '(water|voda)' then ans:=format('%s typically contains about %s ml added water, with an espresso yield of about %s ml.',k.name_en,coalesce(k.recipe->>'water_ml','0'),coalesce(k.recipe->>'espresso_ml','0'));
   elsif t ~ '(caffeine|kofein)' then ans:=format('%s typically contains about %s–%s mg caffeine. The actual amount varies by bean, dose and extraction.',k.name_en,coalesce(k.recipe->>'caffeine_mg_min','—'),coalesce(k.recipe->>'caffeine_mg_max','—'));
   elsif t ~ '(calorie|kalor)' then ans:=format('%s is typically about %s–%s kcal before optional sugar, syrup or toppings. The actual Langar Bar recipe takes priority.',k.name_en,coalesce(k.recipe->>'calories_min','—'),coalesce(k.recipe->>'calories_max','—'));
   else ans:=coalesce(case when p_lang='hr' then k.summary_hr||E'\n\n'||coalesce(k.details_hr,'') else k.summary_en||E'\n\n'||coalesce(k.details_en,'') end,k.name_en); end if;
   r:=to_jsonb(k);
 elsif f.id is not null then
   ans:=case when p_lang='hr' then f.answer_hr else f.answer_en end;
   r:=jsonb_build_object('name_en',case when p_lang='hr' then f.question_hr else f.question_en end,'name_hr',f.question_hr,'recipe','{}'::jsonb);
 elsif k.id is not null then
   ans:=case when p_lang='hr' then k.summary_hr||E'\n\n'||coalesce(k.details_hr,'') else k.summary_en||E'\n\n'||coalesce(k.details_en,'') end;
   r:=to_jsonb(k);
 else
   insert into public.barista_questions(user_id,customer_email,subject,question,status,answer_source,created_at,updated_at)
   values(u.id,u.email,p_subject,p_question,'new','human',now(),now()) returning id into qid;
   return jsonb_build_object('matched',false,'question_id',qid,'sensitive',false);
 end if;
 insert into public.barista_questions(user_id,customer_email,subject,question,status,admin_reply,answer_source,matched_knowledge_id,answered_at,created_at,updated_at)
 values(u.id,u.email,p_subject,p_question,'answered',ans,'knowledge',k.id,now(),now(),now()) returning id into qid;
 return jsonb_build_object('matched',true,'question_id',qid,'answer',ans,'knowledge',r);
end$$;
grant execute on function public.smart_barista_ask_v541(text,text,text) to authenticated;

create or replace function public.list_my_barista_questions_v541()
returns table(id uuid,subject text,question text,status text,answer text,answer_source text,created_at timestamptz,answered_at timestamptz)
language sql stable security definer set search_path=public as $$
 select b.id,b.subject,b.question,b.status,nullif(trim(coalesce(b.admin_reply,'')),'') answer,b.answer_source,b.created_at,b.answered_at
 from public.barista_questions b
 where b.user_id=auth.uid() or lower(b.customer_email)=lower(coalesce(auth.jwt()->>'email',''))
 order by b.created_at desc limit 150
$$;
grant execute on function public.list_my_barista_questions_v541() to authenticated;

create or replace function public.list_suggested_barista_questions_v541(p_lang text default 'en',p_limit integer default 50)
returns table(question text,category text) language sql stable security definer set search_path=public as $$
 select case when p_lang='hr' then question_hr else question_en end,category
 from public.langar_knowledge_faqs where active order by sort_order,question_en limit greatest(1,least(p_limit,50))
$$;
grant execute on function public.list_suggested_barista_questions_v541(text,integer) to authenticated,anon;
