-- Langar Bar V5.1.0 — independent ordering and internal print metadata
-- Safe additive migration. It does not perform fiscalization.

alter table if exists public.customer_orders
  add column if not exists internal_printed_at timestamptz,
  add column if not exists internal_print_count integer not null default 0,
  add column if not exists delivery_copy_printed_at timestamptz,
  add column if not exists fiscal_entry_recorded_at timestamptz,
  add column if not exists fiscal_entry_recorded_by uuid,
  add column if not exists fiscal_receipt_number text;

comment on column public.customer_orders.internal_printed_at is 'Last internal non-fiscal order ticket print time.';
comment on column public.customer_orders.fiscal_entry_recorded_at is 'Manual confirmation that staff entered this order in the currently certified fiscal system.';
comment on column public.customer_orders.fiscal_receipt_number is 'Official receipt reference from the separate certified fiscal system. Not generated by Langar Bar V5.1.0.';

create table if not exists public.order_print_audit (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.customer_orders(id) on delete cascade,
  copy_type text not null check (copy_type in ('internal','delivery','kitchen')),
  printed_by uuid references auth.users(id),
  printed_at timestamptz not null default now(),
  device_label text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.order_print_audit enable row level security;
-- Admin access policy should reuse the project's admin_members model.
do $$ begin
  if to_regclass('public.admin_members') is not null then
    execute $p$create policy "admins_manage_order_print_audit" on public.order_print_audit for all to authenticated using (exists (select 1 from public.admin_members a where a.user_id=auth.uid())) with check (exists (select 1 from public.admin_members a where a.user_id=auth.uid()))$p$;
  end if;
exception when duplicate_object then null; end $$;
